-- POS Quick PIN: user PIN fields + tenant policy settings
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "posPinSettings" JSONB;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinDigest" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinFailedAttempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinLockedUntil" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinUpdatedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pinMustChange" BOOLEAN NOT NULL DEFAULT false;

CREATE UNIQUE INDEX IF NOT EXISTS "User_tenantId_pinDigest_key" ON "User"("tenantId", "pinDigest");
