import { z } from 'zod'
import { INVOICE_TEMPLATE_IDS } from './invoice-settings.util'

const invoiceTemplateSchema = z.enum(INVOICE_TEMPLATE_IDS)

export const updateInvoiceSettingsSchema = z.object({
  invoiceTemplate: invoiceTemplateSchema.optional(),
  shopName: z.string().max(200).optional(),
  companyLegalName: z.string().max(200).optional(),
  vatRegNo: z.string().max(80).optional(),
  qrCodeUrl: z.string().max(500).optional(),
  slogan: z.string().max(500).optional(),
  logo: z.string().max(500).optional(),
  phone: z.string().max(80).optional(),
  email: z.string().max(120).optional(),
  address: z.string().max(500).optional(),
  website: z.string().max(200).optional(),
  bankName: z.string().max(120).optional(),
  accNumber: z.string().max(80).optional(),
  accHolder: z.string().max(120).optional(),
  swiftCode: z.string().max(80).optional(),
  bankDetails: z.string().max(4000).optional(),
  currency: z.string().max(8).optional(),
  taxRate: z.number().min(0).max(100).optional(),
  discountRate: z.number().min(0).max(100).optional(),
  terms: z.array(z.string().max(500)).max(30).optional(),
  warrantyServiceTerms: z.array(z.string().max(800)).max(30).optional(),
  signatoryName: z.string().max(120).optional(),
  signatoryTitle: z.string().max(120).optional(),
  footerNote: z.string().max(500).optional(),
  thermalWidthPOS: z.enum(['58mm', '80mm', 'stockForm']).optional(),
  thermalWidthRepair: z.enum(['58mm', '80mm']).optional(),
  thermalShowLogo: z.boolean().optional(),
  thermalShowSlogan: z.boolean().optional(),
  thermalShowAddress: z.boolean().optional(),
  thermalShowPhone: z.boolean().optional(),
  thermalShowEmail: z.boolean().optional(),
  thermalShowCustomer: z.boolean().optional(),
  thermalShowSku: z.boolean().optional(),
  thermalShowImei: z.boolean().optional(),
  thermalShowPayment: z.boolean().optional(),
  thermalShowBank: z.boolean().optional(),
  thermalShowWebsite: z.boolean().optional(),
  thermalShowWarranty: z.boolean().optional(),
  thermalFontSize: z.enum(['sm', 'md', 'lg']).optional(),
  thermalLogoSize: z.enum(['sm', 'md', 'lg', 'xl']).optional(),
  repairWarrantyMonths: z.number().min(0).max(120).optional(),
  repairIntakeTerms: z.array(z.string().max(800)).max(30).optional(),
  posAutoPrintBill: z.boolean().optional(),
  barcodeLabel: z.object({
    widthMm: z.number().min(20).max(100).optional(),
    heightMm: z.number().min(10).max(80).optional(),
    preset: z.enum(['compact', 'standard', 'detailed', '38x25', '50x30', '40x30', 'custom']).optional(),
    showShopName: z.boolean().optional(),
    showProductName: z.boolean().optional(),
    showSku: z.boolean().optional(),
    showPrice: z.boolean().optional(),
    showBarcodeText: z.boolean().optional(),
    showCopyIndex: z.boolean().optional(),
    nameFontPt: z.number().min(4).max(12).optional(),
    barcodeHeight: z.number().min(12).max(60).optional(),
    barcodeBarWidth: z.number().min(0.6).max(2.5).optional(),
    nameMaxLines: z.union([z.literal(1), z.literal(2)]).optional(),
  }).optional(),
})
