/** Per-menu-item sidebar guide — one step group per sidebar link. */

type SidebarStepGroup = {
  titleEn: string
  titleSi: string
  stepsEn: string[]
  stepsSi: string[]
}

function item(
  titleEn: string,
  titleSi: string,
  en: { what: string; when: string; open: string; use: string; tip: string },
  si: { what: string; when: string; open: string; use: string; tip: string },
): SidebarStepGroup {
  return {
    titleEn,
    titleSi,
    stepsEn: [
      `What: ${en.what}`,
      `When to use: ${en.when}`,
      `How to open: ${en.open}`,
      `How to use: ${en.use}`,
      `Tip: ${en.tip}`,
    ],
    stepsSi: [
      `මොකක්ද: ${si.what}`,
      `කවදා use කරන්නේ: ${si.when}`,
      `open කරන්නේ: ${si.open}`,
      `use කරන හැටි: ${si.use}`,
      `Tip: ${si.tip}`,
    ],
  }
}

export const SIDEBAR_GUIDE_STEP_GROUPS: SidebarStepGroup[] = [
  // ── Header (top bar) ──
  item(
    'HEADER — Branch selector',
    'HEADER — Branch selector',
    {
      what: 'Picks which shop branch you are working on. Sales, stock, and reports follow this branch.',
      when: 'Every login — especially if you manage more than one branch.',
      open: 'Top header bar → branch name dropdown (next to shop logo area).',
      use: 'Click branch name → select your branch → all pages refresh for that branch.',
      tip: 'Wrong branch selected = wrong stock and sales numbers. Always check before POS.',
    },
    {
      what: 'ඔබ වැඩ කරන shop branch එක select කරනවා. Sales, stock, reports මේ branch අනුව.',
      when: 'Login වෙනකොට — branch කිහිපයක් manage කරන shops.',
      open: 'Header bar → branch name dropdown.',
      use: 'Branch click → select → pages refresh.',
      tip: 'Branch වැරදි නම් stock/sales numbers වැරදි. POS එකට පෙර check.',
    },
  ),
  item(
    'HEADER — POS Terminal (F2)',
    'HEADER — POS Terminal (F2)',
    {
      what: 'Quick button to open the sales/checkout screen from anywhere in the dashboard.',
      when: 'When a customer is waiting and you need to start billing fast.',
      open: 'Top header → POS Terminal button, or press F2 on keyboard.',
      use: 'Click or F2 → POS screen opens → add products and checkout as normal.',
      tip: 'F2 works on most dashboard pages — faster than scrolling the sidebar.',
    },
    {
      what: 'Dashboard එකේ ඕනෑ තැනකින් POS/sales screen ඉක්මනින් open.',
      when: 'Customer wait කරනකොට billing ඉක්මනින් start.',
      open: 'Header → POS Terminal හෝ keyboard F2.',
      use: 'Click/F2 → POS open → products add → checkout.',
      tip: 'F2 sidebar scroll කරන්න වඩා fast.',
    },
  ),

  // ── Overview ──
  item(
    'OVERVIEW — Dashboard',
    'OVERVIEW — Dashboard',
    {
      what: 'Home screen — today\'s sales, profit, repairs, stock alerts, and quick shortcuts.',
      when: 'Start of day, after lunch, and before closing — to see shop health at a glance.',
      open: 'Sidebar → Overview → Dashboard (first menu item).',
      use: 'Read today totals → check low-stock alerts → click shortcuts to jump to POS, Inventory, or Repairs.',
      tip: 'Shop Quest Mission 2 highlights this — daily pulse check before selling.',
    },
    {
      what: 'Home screen — අද sales, profit, repairs, stock alerts, shortcuts.',
      when: 'දවස start, lunch එකට පස්සේ, close කරන්න කලින්.',
      open: 'Sidebar → Dashboard.',
      use: 'Today totals → stock alerts → shortcuts click → POS/Inventory/Repairs.',
      tip: 'Shop Quest Mission 2 — daily pulse check.',
    },
  ),

  // ── Sales ──
  item(
    'SALES — Point of Sale (POS)',
    'SALES — Point of Sale (POS)',
    {
      what: 'Main checkout screen — add products, customer, payment, print bill.',
      when: 'Every time you sell something to a customer.',
      open: 'Sidebar → Point of Sale, header POS Terminal, or F2.',
      use: 'Add products → F2 customer → edit price/warranty if needed → F9 Checkout → payment → bill prints.',
      tip: 'See User Manual → POS section for full keyboard shortcuts (F5 reprint, F10 new sale).',
    },
    {
      what: 'Main checkout — products, customer, payment, bill print.',
      when: 'Customer එකට ඕනෑම දෙයක් විකුණන වෙලාව.',
      open: 'Sidebar → Point of Sale / F2.',
      use: 'Products add → F2 customer → F9 checkout → payment → bill.',
      tip: 'User Manual → POS — F5, F10 shortcuts.',
    },
  ),
  item(
    'SALES — Sales History',
    'SALES — Sales History',
    {
      what: 'List of all past invoices — search, view details, reprint or download PDF.',
      when: 'Customer lost bill, needs duplicate, or you need to verify an old sale.',
      open: 'Sidebar → Sales → Sales History.',
      use: 'Search by invoice no, customer phone, or date → open row → Reprint or Download PDF.',
      tip: 'F5 in POS only reprints the last bill — use Sales History for older invoices.',
    },
    {
      what: 'පරණ invoices list — search, reprint, PDF.',
      when: 'Bill නැති වුණා, duplicate ඕන, පරණ sale verify.',
      open: 'Sidebar → Sales History.',
      use: 'Invoice no / phone / date search → row open → Reprint/PDF.',
      tip: 'F5 last bill only — පරණ bills Sales History.',
    },
  ),
  item(
    'SALES — Returns',
    'SALES — Returns',
    {
      what: 'Return items from a previous sale — stock and IMEI restore automatically.',
      when: 'Customer brings back a product (defect, wrong item, refund policy).',
      open: 'Sidebar → Sales → Returns.',
      use: 'Find original invoice → select items and qty to return → confirm → stock/IMEI restores → process refund.',
      tip: 'Always find the original sale first — do not create a manual stock adjustment for returns.',
    },
    {
      what: 'පරණ sale එකෙන් items return — stock/IMEI auto restore.',
      when: 'Customer product return/refund.',
      open: 'Sidebar → Returns.',
      use: 'Original invoice find → items select → confirm → refund.',
      tip: 'Original sale find කරන්න — manual stock adjust නෙමෙයි.',
    },
  ),
  item(
    'SALES — Customers',
    'SALES — Customers',
    {
      what: 'Customer database — name, phone, address, credit/outstanding balance.',
      when: 'Before credit sales, warranty sales, or when adding regular customers.',
      open: 'Sidebar → Sales → Customers.',
      use: 'Add Customer → fill name + phone → Save. In POS press F2 to search same customers quickly.',
      tip: 'Phone number is the main search key in POS — always enter it correctly.',
    },
    {
      what: 'Customer database — name, phone, address, outstanding balance.',
      when: 'Credit/warranty sales කලින්, regular customers add.',
      open: 'Sidebar → Customers.',
      use: 'Add Customer → name + phone → Save. POS F2 search.',
      tip: 'Phone number POS search key — correctly enter.',
    },
  ),
  item(
    'SALES — Services',
    'SALES — Services',
    {
      what: 'Sell non-stock services — screen guard fitting, software install, labour charges (if enabled).',
      when: 'You charge for work that is not a physical product in inventory.',
      open: 'Sidebar → Sales → Services (visible only if SERVICES feature enabled).',
      use: 'Create or pick service item → add to sale flow or bill as service charge per your shop setup.',
      tip: 'If you do not see this menu, ask Owner to enable Services in Settings → Features.',
    },
    {
      what: 'Stock නැති services විකුණන්න — screen guard, software, labour (enabled නම්).',
      when: 'Physical product නෙමෙයි service charge.',
      open: 'Sidebar → Services (feature enabled නම්).',
      use: 'Service item create/pick → sale flow.',
      tip: 'Menu නැත්තොත් Settings → Features enable.',
    },
  ),

  // ── Inventory ──
  item(
    'INVENTORY — All Products',
    'INVENTORY — All Products',
    {
      what: 'Full product list — stock qty, prices, search, filters, and row actions.',
      when: 'Check stock before selling, find a product, or open product details.',
      open: 'Sidebar → Inventory → All Products (click Inventory to expand submenu).',
      use: 'Search by name/SKU → view stock level → Add Stock, edit, or open IMEI list from row actions.',
      tip: 'Low stock alerts on Dashboard link back here — keep quantities updated.',
    },
    {
      what: 'Product list — stock, prices, search, filters.',
      when: 'Stock check, product find, details.',
      open: 'Sidebar → Inventory → All Products.',
      use: 'Search → stock view → Add Stock / edit / IMEI.',
      tip: 'Dashboard low stock alerts — quantities update කරන්න.',
    },
  ),
  item(
    'INVENTORY — Add Product',
    'INVENTORY — Add Product',
    {
      what: 'Create a new product — phone, part, accessory with price, warranty, IMEI, variants.',
      when: 'First time stocking a new model or item not yet in the system.',
      open: 'Sidebar → Inventory → Add Product.',
      use: 'Fill name, brand, category, selling price, cost, opening stock → enable IMEI for phones → Save.',
      tip: 'Use Purchase Order receive for repeat restock — Add Product is mainly for new SKUs.',
    },
    {
      what: 'නව product create — phone, part, accessory, price, warranty, IMEI.',
      when: 'නව model/item system එකේ නැති වෙලාව.',
      open: 'Sidebar → Inventory → Add Product.',
      use: 'Name, brand, price, stock, IMEI enable → Save.',
      tip: 'Repeat restock PO receive — Add Product new SKUs.',
    },
  ),
  item(
    'INVENTORY — Stock Transfer',
    'INVENTORY — Stock Transfer',
    {
      what: 'Move stock quantity from one branch to another (multi-branch shops).',
      when: 'Branch A has extra stock and Branch B needs it.',
      open: 'Sidebar → Inventory → Stock Transfer.',
      use: 'Select product → from branch → to branch → qty → confirm transfer → both branches update.',
      tip: 'Only visible for multi-branch shops. Single-branch shops will not use this.',
    },
    {
      what: 'Branch අතර stock move (multi-branch).',
      when: 'Branch එකක extra, අනිත් branch එකට ඕන.',
      open: 'Sidebar → Inventory → Stock Transfer.',
      use: 'Product → from/to branch → qty → confirm.',
      tip: 'Multi-branch shops only.',
    },
  ),
  item(
    'INVENTORY — All Suppliers',
    'INVENTORY — All Suppliers',
    {
      what: 'Supplier contacts — name, phone, address, and purchase history.',
      when: 'Adding a new wholesaler or checking who you buy from.',
      open: 'Sidebar → Inventory → Suppliers → All Suppliers.',
      use: 'Add Supplier → fill details → Save → use when creating Purchase Orders.',
      tip: 'Keep supplier phone updated — helps when chasing delayed deliveries.',
    },
    {
      what: 'Supplier contacts — name, phone, purchase history.',
      when: 'නව wholesaler add, supplier details check.',
      open: 'Sidebar → Suppliers → All Suppliers.',
      use: 'Add Supplier → details → Save → PO create.',
      tip: 'Phone update — delayed delivery follow up.',
    },
  ),
  item(
    'INVENTORY — Supplier Payments',
    'INVENTORY — Supplier Payments',
    {
      what: 'Pay supplier balances — record payments linked to purchase orders.',
      when: 'You pay the wholesaler for goods received on credit.',
      open: 'Sidebar → Inventory → Suppliers → Supplier Payments.',
      use: 'Select supplier → enter payment amount and method → link to PO if applicable → Save.',
      tip: 'Paying without recording here makes Finance reports wrong.',
    },
    {
      what: 'Supplier balance pay — PO link.',
      when: 'Wholesaler credit payment record.',
      open: 'Sidebar → Supplier Payments.',
      use: 'Supplier select → amount → method → PO link → Save.',
      tip: 'Record නැතුව pay කළොත් Finance reports වැරදි.',
    },
  ),
  item(
    'INVENTORY — Purchase Orders',
    'INVENTORY — Purchase Orders',
    {
      what: 'Order stock from suppliers — create PO, receive goods, stock increases.',
      when: 'New shipment arriving from wholesaler — restock inventory.',
      open: 'Sidebar → Inventory → Purchase Orders.',
      use: 'New PO → pick supplier + products + qty → Save → when goods arrive click Receive → stock updates.',
      tip: 'Receive PO on the day goods arrive — do not leave POs open after stock is in the shop.',
    },
    {
      what: 'Supplier stock order — PO create, receive, stock increase.',
      when: 'Wholesaler shipment restock.',
      open: 'Sidebar → Purchase Orders.',
      use: 'New PO → supplier + products → Receive when goods arrive.',
      tip: 'Goods ආවම Receive — open PO තියන්න එපා.',
    },
  ),
  item(
    'INVENTORY — IMEI Tracker',
    'INVENTORY — IMEI Tracker',
    {
      what: 'Track every phone IMEI — in stock, sold, linked to warranty and customer.',
      when: 'Find a specific phone, verify IMEI before sale, or audit stock.',
      open: 'Sidebar → Inventory → IMEI Tracker.',
      use: 'Search IMEI → see status (in stock / sold) → open linked sale or warranty if sold.',
      tip: 'Scan IMEI in POS when selling — tracker updates automatically on sale.',
    },
    {
      what: 'Phone IMEI track — stock, sold, warranty link.',
      when: 'Specific phone find, IMEI verify, audit.',
      open: 'Sidebar → IMEI Tracker.',
      use: 'IMEI search → status → sale/warranty link.',
      tip: 'POS IMEI scan — sale එකේ auto update.',
    },
  ),

  // ── Service ──
  item(
    'SERVICE — Repair Jobs',
    'SERVICE — Repair Jobs',
    {
      what: 'Repair ticket system — receive device, diagnose, repair, collect payment, deliver.',
      when: 'Customer leaves a phone/device for repair.',
      open: 'Sidebar → Service → Repair Jobs.',
      use: 'New Repair → customer + device + fault → work through statuses → add parts → Ready → Collect Payment → Delivered.',
      tip: 'Full step guide in User Manual → Repair Jobs section.',
    },
    {
      what: 'Repair tickets — receive, repair, payment, deliver.',
      when: 'Customer device repair එකට දෙනවා.',
      open: 'Sidebar → Repair Jobs.',
      use: 'New Repair → statuses → parts → payment → delivered.',
      tip: 'User Manual → Repair Jobs full guide.',
    },
  ),
  item(
    'SERVICE — Warranty',
    'SERVICE — Warranty',
    {
      what: 'Warranty certificates from sales — view active/expired, process claims.',
      when: 'Customer asks about warranty status or brings device for warranty claim.',
      open: 'Sidebar → Service → Warranty.',
      use: 'Search by customer phone or IMEI → open certificate → check dates → process claim if valid.',
      tip: 'Warranty auto-creates on POS sale when customer selected and product has warranty months.',
    },
    {
      what: 'Warranty certificates — status, claims.',
      when: 'Customer warranty check/claim.',
      open: 'Sidebar → Warranty.',
      use: 'Phone/IMEI search → certificate → claim process.',
      tip: 'POS sale + customer + warranty months → auto create.',
    },
  ),
  item(
    'SERVICE — Device Exchange',
    'SERVICE — Device Exchange',
    {
      what: 'Swap/trade-in customer device under your shop exchange policy (if enabled).',
      when: 'Customer upgrades phone and trades old device.',
      open: 'Sidebar → Service → Device Exchange (if EXCHANGES feature enabled).',
      use: 'Start exchange → record old device + new sale → apply exchange value per shop rules.',
      tip: 'Not all shops use this — enable in Settings if you run exchange programs.',
    },
    {
      what: 'Device swap/trade-in (enabled නම්).',
      when: 'Customer upgrade + old phone trade.',
      open: 'Sidebar → Device Exchange.',
      use: 'Exchange start → old device + new sale → value apply.',
      tip: 'Settings → enable if exchange program.',
    },
  ),

  // ── Finance (main items) ──
  item(
    'FINANCE — Finance',
    'FINANCE — Finance',
    {
      what: 'Cash flow summary — money in and out by date range.',
      when: 'Review daily or weekly shop money movement.',
      open: 'Sidebar → Finance → Finance.',
      use: 'Pick date range → view income vs expenses summary → drill into linked records.',
      tip: 'Pair with Expenses and Daily Closing for complete picture.',
    },
    {
      what: 'Cash flow summary — money in/out by date.',
      when: 'Daily/weekly money movement review.',
      open: 'Sidebar → Finance.',
      use: 'Date range → income/expense summary.',
      tip: 'Expenses + Daily Closing එක්ක use.',
    },
  ),
  item(
    'FINANCE — Profit & Loss',
    'FINANCE — Profit & Loss',
    {
      what: 'Revenue vs cost report — see if the shop is making profit.',
      when: 'End of week/month or when Owner reviews performance.',
      open: 'Sidebar → Finance → Profit & Loss.',
      use: 'Select period → read revenue, cost of goods, expenses, net profit.',
      tip: 'Accurate P&L needs correct cost prices on products and recorded expenses.',
    },
    {
      what: 'Revenue vs cost — profit report.',
      when: 'Week/month end Owner review.',
      open: 'Sidebar → Profit & Loss.',
      use: 'Period select → revenue, cost, net profit.',
      tip: 'Cost prices + expenses correct නම් P&L accurate.',
    },
  ),
  item(
    'FINANCE — Expenses',
    'FINANCE — Expenses',
    {
      what: 'Record shop running costs — rent, electricity, salaries, supplies.',
      when: 'Whenever the shop pays a business expense.',
      open: 'Sidebar → Finance → Expenses.',
      use: 'Add Expense → amount, category, date, note → Save.',
      tip: 'Record on the day you pay — waiting makes month-end reports wrong.',
    },
    {
      what: 'Shop expenses record — rent, bills, supplies.',
      when: 'Business expense pay කරන වෙලාව.',
      open: 'Sidebar → Expenses.',
      use: 'Add Expense → amount, category, date → Save.',
      tip: 'Pay කරන දවසේ record — delay reports වැරදි.',
    },
  ),
  item(
    'FINANCE — Profit Allocation',
    'FINANCE — Profit Allocation',
    {
      what: 'Split profit into internal funds/pools (if enabled on your plan).',
      when: 'Owner distributes profit to partners, savings, or reinvestment buckets.',
      open: 'Sidebar → Finance → Profit Allocation (if PROFIT_ALLOCATION enabled).',
      use: 'Define funds → allocate amounts from period profit per shop rules.',
      tip: 'Most small shops skip this — only use if Owner set it up.',
    },
    {
      what: 'Profit internal funds වලට split (enabled නම්).',
      when: 'Owner profit distribute/partners.',
      open: 'Sidebar → Profit Allocation.',
      use: 'Funds define → profit allocate.',
      tip: 'Small shops often skip — Owner setup නම් use.',
    },
  ),
  item(
    'FINANCE — Daily Closing',
    'FINANCE — Daily Closing',
    {
      what: 'End-of-day cash count — close business day and lock daily totals.',
      when: 'Every night when shop closes (or press F11 in POS).',
      open: 'Sidebar → Finance → Daily Closing, or F11 in POS.',
      use: 'Count cash by denomination → enter amounts → compare with system expected → close day.',
      tip: 'Do not skip — next day sales reports start clean after closing.',
    },
    {
      what: 'Day end cash count — business day close.',
      when: 'Shop close (F11 POS).',
      open: 'Sidebar → Daily Closing / F11.',
      use: 'Cash count → enter → expected vs actual → close.',
      tip: 'Skip නොකරන්න — next day clean start.',
    },
  ),

  // ── Hire Purchase submenu ──
  item(
    'FINANCE — HP Dashboard',
    'FINANCE — HP Dashboard',
    {
      what: 'Hire Purchase home — active agreements, today collections, overdue summary.',
      when: 'Start of day when shop runs installment sales.',
      open: 'Sidebar → Finance → Hire Purchase → HP Dashboard.',
      use: 'Review alerts → jump to Due Collections or Defaulters from summary cards.',
      tip: 'Only visible if HIRE_PURCHASE feature enabled.',
    },
    {
      what: 'HP home — agreements, collections, overdue summary.',
      when: 'Installment sales shop — day start.',
      open: 'Sidebar → Hire Purchase → HP Dashboard.',
      use: 'Alerts review → Due/Defaulters jump.',
      tip: 'HIRE_PURCHASE enabled නම් පමණි.',
    },
  ),
  item(
    'FINANCE — HP Agreements',
    'FINANCE — HP Agreements',
    {
      what: 'Create and manage installment contracts — down payment + monthly dues.',
      when: 'Customer buys on installments instead of full cash at POS.',
      open: 'Sidebar → Hire Purchase → Agreements.',
      use: 'New Agreement → customer + product + down payment + monthly amount + months → Save → collect down payment.',
      tip: 'See User Manual → Hire Purchase for full 4-step flow.',
    },
    {
      what: 'Installment contracts — down payment + monthly dues.',
      when: 'Full cash නැතුව installments.',
      open: 'Sidebar → Agreements.',
      use: 'New → customer + product + terms → Save.',
      tip: 'User Manual → Hire Purchase full flow.',
    },
  ),
  item(
    'FINANCE — HP Payment Collection',
    'FINANCE — HP Payment Collection',
    {
      what: 'Record when customer pays their monthly installment.',
      when: 'Customer comes to pay HP due.',
      open: 'Sidebar → Hire Purchase → Payment Collection.',
      use: 'Select agreement → enter amount paid → Save → balance reduces.',
      tip: 'Always pick the correct agreement — phone search helps.',
    },
    {
      what: 'Monthly installment payment record.',
      when: 'Customer HP due pay කරනවා.',
      open: 'Sidebar → Payment Collection.',
      use: 'Agreement select → amount → Save.',
      tip: 'Correct agreement select — phone search.',
    },
  ),
  item(
    'FINANCE — HP Due Collections',
    'FINANCE — HP Due Collections',
    {
      what: 'List of installments due today or this period — who to collect from.',
      when: 'Morning planning — call/collect from due customers.',
      open: 'Sidebar → Hire Purchase → Due Collections.',
      use: 'Filter by date → see due list → collect payment → record in Payment Collection.',
      tip: 'Work this list daily — reduces defaulters.',
    },
    {
      what: 'Today/period due installments list.',
      when: 'Morning — collect plan.',
      open: 'Sidebar → Due Collections.',
      use: 'Due list → collect → Payment Collection record.',
      tip: 'Daily list work — defaulters reduce.',
    },
  ),
  item(
    'FINANCE — HP Defaulters',
    'FINANCE — HP Defaulters',
    {
      what: 'Customers who missed payments or are overdue.',
      when: 'Follow-up calls and recovery tracking.',
      open: 'Sidebar → Hire Purchase → Defaulters.',
      use: 'Review list → call customer/guarantor → record partial payments when received.',
      tip: 'Cross-check with Guarantors page for backup contacts.',
    },
    {
      what: 'Missed/overdue HP customers.',
      when: 'Follow-up calls, recovery.',
      open: 'Sidebar → Defaulters.',
      use: 'List review → call → partial payment record.',
      tip: 'Guarantors page cross-check.',
    },
  ),
  item(
    'FINANCE — HP Guarantors',
    'FINANCE — HP Guarantors',
    {
      what: 'People who guarantee the HP agreement if buyer defaults.',
      when: 'Creating agreement or chasing defaulters.',
      open: 'Sidebar → Hire Purchase → Guarantors.',
      use: 'Add guarantor on agreement → contact when buyer misses payment.',
      tip: 'Collect guarantor phone at agreement time — saves recovery time later.',
    },
    {
      what: 'HP agreement guarantee දෙන අය.',
      when: 'Agreement create / defaulter follow up.',
      open: 'Sidebar → Guarantors.',
      use: 'Agreement එකේ guarantor add → contact.',
      tip: 'Agreement time phone collect.',
    },
  ),
  item(
    'FINANCE — HP Reports',
    'FINANCE — HP Reports',
    {
      what: 'HP collection reports, outstanding balances, agreement status.',
      when: 'Owner review or month-end HP summary.',
      open: 'Sidebar → Hire Purchase → HP Reports.',
      use: 'Pick report type and date range → export or review on screen.',
      tip: 'Use with HP Dashboard for daily vs monthly view.',
    },
    {
      what: 'HP collection, outstanding, status reports.',
      when: 'Owner review / month end.',
      open: 'Sidebar → HP Reports.',
      use: 'Report type + date → review/export.',
      tip: 'HP Dashboard daily + Reports monthly.',
    },
  ),
  item(
    'FINANCE — HP Settings',
    'FINANCE — HP Settings',
    {
      what: 'Down payment rules, penalty/interest, agreement numbering.',
      when: 'First time enabling HP or changing shop HP policy.',
      open: 'Sidebar → Hire Purchase → HP Settings.',
      use: 'Set rules → Save before creating new agreements.',
      tip: 'Changing settings does not rewrite old agreements — only new ones.',
    },
    {
      what: 'Down payment rules, penalty, numbering.',
      when: 'HP first setup / policy change.',
      open: 'Sidebar → HP Settings.',
      use: 'Rules set → Save → agreements create.',
      tip: 'Old agreements change නොවෙයි — new only.',
    },
  ),

  // ── Accounting submenu ──
  item(
    'FINANCE — Accounting Overview',
    'FINANCE — Accounting Overview',
    {
      what: 'GL home — chart of accounts snapshot, recent journals, key balances.',
      when: 'Daily check when shop runs full double-entry accounting.',
      open: 'Sidebar → Finance → Accounting → Overview.',
      use: 'Scan recent auto-posted entries from POS/suppliers → verify balances look correct.',
      tip: 'Only for shops with ACCOUNTING feature — not needed for basic POS-only shops.',
    },
    {
      what: 'GL home — accounts snapshot, journals, balances.',
      when: 'Full accounting run shops — daily check.',
      open: 'Sidebar → Accounting → Overview.',
      use: 'Recent entries → balances verify.',
      tip: 'ACCOUNTING feature shops only.',
    },
  ),
  item(
    'FINANCE — GL Journals',
    'FINANCE — GL Journals',
    {
      what: 'Manual journal entries — debit and credit lines for adjustments.',
      when: 'Correct errors, transfer between accounts, non-POS adjustments.',
      open: 'Sidebar → Accounting → GL Journals.',
      use: 'New Journal → add debit + credit lines → totals must balance → post.',
      tip: 'Debits must equal credits — system will reject unbalanced entries.',
    },
    {
      what: 'Manual debit/credit journal entries.',
      when: 'Adjustments, corrections, transfers.',
      open: 'Sidebar → GL Journals.',
      use: 'New Journal → debit/credit balance → post.',
      tip: 'Debit = Credit — unbalanced reject.',
    },
  ),
  item(
    'FINANCE — GL Reports',
    'FINANCE — GL Reports',
    {
      what: 'Trial balance, P&L, balance sheet from general ledger.',
      when: 'Month end, auditor request, or Owner financial review.',
      open: 'Sidebar → Accounting → GL Reports.',
      use: 'Select report + period → run → export if needed.',
      tip: 'Run Trial Balance first — debits must equal credits before trusting P&L.',
    },
    {
      what: 'Trial balance, P&L, balance sheet.',
      when: 'Month end, audit, Owner review.',
      open: 'Sidebar → GL Reports.',
      use: 'Report + period → run → export.',
      tip: 'Trial Balance first — debit=credit.',
    },
  ),
  item(
    'FINANCE — AR / AP',
    'FINANCE — AR / AP',
    {
      what: 'Accounts Receivable (customers owe you) and Payable (you owe suppliers).',
      when: 'Track outstanding customer credit and supplier bills.',
      open: 'Sidebar → Accounting → AR / AP.',
      use: 'Review receivable/payable lists → match with Customers outstanding and Supplier Payments.',
      tip: 'AR should match credit customer balances on Customers page.',
    },
    {
      what: 'Receivable (customers owe) / Payable (you owe suppliers).',
      when: 'Credit customers + supplier bills track.',
      open: 'Sidebar → AR / AP.',
      use: 'Lists review → Customers/Supplier Payments match.',
      tip: 'AR = Customers outstanding match.',
    },
  ),
  item(
    'FINANCE — Cash & Bank',
    'FINANCE — Cash & Bank',
    {
      what: 'Track cash drawers and bank accounts — deposits, withdrawals, reconcile.',
      when: 'Bank deposit, transfer, or reconcile with bank statement.',
      open: 'Sidebar → Accounting → Cash & Bank.',
      use: 'Record deposit/withdrawal → mark reconciled when matched to bank statement.',
      tip: 'Daily Closing handles shop drawer — Cash & Bank is for formal ledger accounts.',
    },
    {
      what: 'Cash drawers + bank accounts — deposits, reconcile.',
      when: 'Bank deposit, statement reconcile.',
      open: 'Sidebar → Cash & Bank.',
      use: 'Deposit/withdrawal record → reconcile.',
      tip: 'Daily Closing drawer — Cash & Bank formal ledger.',
    },
  ),
  item(
    'FINANCE — VAT / Tax',
    'FINANCE — VAT / Tax',
    {
      what: 'Tax entries and reports for VAT-registered shops.',
      when: 'Filing VAT returns or recording tax on purchases/sales.',
      open: 'Sidebar → Accounting → VAT / Tax.',
      use: 'Enter tax transactions → run tax reports before filing.',
      tip: 'Only needed if shop is VAT registered — others can ignore.',
    },
    {
      what: 'VAT tax entries + reports.',
      when: 'VAT filing, tax record.',
      open: 'Sidebar → VAT / Tax.',
      use: 'Tax entries → reports run.',
      tip: 'VAT registered shops only.',
    },
  ),
  item(
    'FINANCE — Petty Cash',
    'FINANCE — Petty Cash',
    {
      what: 'Small daily expenses paid from petty cash float.',
      when: 'Tea, transport, small supplies paid from cash float.',
      open: 'Sidebar → Accounting → Petty Cash.',
      use: 'Record expense against petty cash account → float balance reduces.',
      tip: 'Replenish float periodically — record top-up as journal if needed.',
    },
    {
      what: 'Petty cash float small expenses.',
      when: 'Tea, transport, small supplies.',
      open: 'Sidebar → Petty Cash.',
      use: 'Expense record → float reduce.',
      tip: 'Float replenish — journal top-up.',
    },
  ),
  item(
    'FINANCE — Payroll',
    'FINANCE — Payroll',
    {
      what: 'Staff salary records and payroll journals.',
      when: 'Monthly salary run through the system.',
      open: 'Sidebar → Accounting → Payroll.',
      use: 'Enter salary period → staff amounts → post payroll journal.',
      tip: 'Many shops pay cash and only record in Expenses — use Payroll if you need GL detail.',
    },
    {
      what: 'Staff salary + payroll journals.',
      when: 'Monthly salary system එකෙන්.',
      open: 'Sidebar → Payroll.',
      use: 'Period → staff amounts → post.',
      tip: 'Cash pay shops Expenses use — GL detail Payroll.',
    },
  ),
  item(
    'FINANCE — Accounting Periods',
    'FINANCE — Accounting Periods',
    {
      what: 'Open/close accounting months — lock past periods from edits.',
      when: 'Month end after reports are finalized.',
      open: 'Sidebar → Accounting → Periods.',
      use: 'Close completed month → past journals cannot be changed accidentally.',
      tip: 'Close only after Owner reviews GL Reports — reopening may need admin help.',
    },
    {
      what: 'Accounting months open/close — past lock.',
      when: 'Month end reports finalize.',
      open: 'Sidebar → Periods.',
      use: 'Month close → past edits lock.',
      tip: 'GL Reports review පස්සේ close.',
    },
  ),
  item(
    'FINANCE — Audit Trail',
    'FINANCE — Audit Trail',
    {
      what: 'Log of who changed what in accounting — for control and review.',
      when: 'Suspicious balance change or Owner audit.',
      open: 'Sidebar → Accounting → Audit Trail.',
      use: 'Filter by date/user → review change history.',
      tip: 'Check here before blaming staff — shows exact edits.',
    },
    {
      what: 'Accounting changes log — who changed what.',
      when: 'Balance issue, Owner audit.',
      open: 'Sidebar → Audit Trail.',
      use: 'Date/user filter → history review.',
      tip: 'Staff blame කරන්න කලින් check.',
    },
  ),
  item(
    'FINANCE — Accounting Settings',
    'FINANCE — Accounting Settings',
    {
      what: 'Fiscal year, default accounts, posting rules for GL.',
      when: 'First-time accounting setup or year change.',
      open: 'Sidebar → Accounting → Settings.',
      use: 'Set fiscal year start → default accounts → posting rules → Save.',
      tip: 'Wrong defaults cause every auto-post to hit wrong account — set carefully once.',
    },
    {
      what: 'Fiscal year, default accounts, posting rules.',
      when: 'Accounting first setup / year change.',
      open: 'Sidebar → Accounting → Settings.',
      use: 'Fiscal year + defaults → Save.',
      tip: 'Defaults wrong නම් auto-post wrong account.',
    },
  ),

  // ── Reports submenu ──
  item(
    'REPORTS — Overview',
    'REPORTS — Overview',
    {
      what: 'Reports home — quick links to all report types.',
      when: 'Starting any analysis — pick the report you need.',
      open: 'Sidebar → Reports & Analytics → Overview.',
      use: 'Click report tile → set filters → view or export.',
      tip: 'Requires REPORTS feature on your plan.',
    },
    {
      what: 'Reports home — all report links.',
      when: 'Analysis start — report pick.',
      open: 'Sidebar → Reports & Analytics → Overview.',
      use: 'Report tile → filters → view/export.',
      tip: 'REPORTS feature required.',
    },
  ),
  item(
    'REPORTS — Sales Report',
    'REPORTS — Sales Report',
    {
      what: 'Sales breakdown by date, product, staff, or payment method.',
      when: 'Review what sold best or compare days.',
      open: 'Sidebar → Reports & Analytics → Sales.',
      use: 'Set date range and filters → run report → export Excel if needed.',
      tip: 'Match a slow day against Dashboard to find cause (stock out, closed shop).',
    },
    {
      what: 'Sales breakdown — date, product, staff.',
      when: 'Best sellers, day compare.',
      open: 'Sidebar → Reports → Sales.',
      use: 'Date range → run → export.',
      tip: 'Slow day Dashboard match — stock out check.',
    },
  ),
  item(
    'REPORTS — P&L Report',
    'REPORTS — P&L Report',
    {
      what: 'Profit and loss from report module (may differ from Finance P&L view).',
      when: 'Owner monthly review with export for accountant.',
      open: 'Sidebar → Reports & Analytics → P&L Report.',
      use: 'Select period → review revenue, costs, net profit → export.',
      tip: 'Ensure expenses and cost prices are entered for accurate profit.',
    },
    {
      what: 'P&L report module view.',
      when: 'Owner monthly review, accountant export.',
      open: 'Sidebar → Reports → P&L Report.',
      use: 'Period → review → export.',
      tip: 'Expenses + cost prices accurate නම් profit accurate.',
    },
  ),
  item(
    'REPORTS — Cash Flow Report',
    'REPORTS — Cash Flow Report',
    {
      what: 'Money in vs out over time — cash movement analysis.',
      when: 'Checking liquidity or planning payments.',
      open: 'Sidebar → Reports & Analytics → Cash Flow.',
      use: 'Pick period → view inflows/outflows chart and table.',
      tip: 'Large supplier payment days show as outflow spikes — normal if PO paid.',
    },
    {
      what: 'Money in/out over time.',
      when: 'Liquidity check, payment plan.',
      open: 'Sidebar → Reports → Cash Flow.',
      use: 'Period → inflow/outflow view.',
      tip: 'Supplier payment days outflow spike — normal.',
    },
  ),
  item(
    'REPORTS — Inventory Report',
    'REPORTS — Inventory Report',
    {
      what: 'Stock levels, valuation, movement — inventory analysis.',
      when: 'Stock take, dead stock review, or valuation.',
      open: 'Sidebar → Reports & Analytics → Inventory.',
      use: 'Run report → compare with physical stock on shelf.',
      tip: 'Discrepancy means unrecorded sales, theft, or missing receive — investigate.',
    },
    {
      what: 'Stock levels, valuation, movement.',
      when: 'Stock take, dead stock review.',
      open: 'Sidebar → Reports → Inventory.',
      use: 'Report run → physical stock compare.',
      tip: 'Mismatch — unrecorded sale/theft/missing receive.',
    },
  ),
  item(
    'REPORTS — Repairs Report',
    'REPORTS — Repairs Report',
    {
      what: 'Repair job stats — turnaround, revenue, technician workload.',
      when: 'Review repair department performance.',
      open: 'Sidebar → Reports & Analytics → Repairs.',
      use: 'Filter by date/technician → see open vs completed jobs.',
      tip: 'Long open jobs list = follow up with technicians on stuck tickets.',
    },
    {
      what: 'Repair stats — turnaround, revenue, workload.',
      when: 'Repair department performance review.',
      open: 'Sidebar → Reports → Repairs.',
      use: 'Date/technician filter → open vs completed.',
      tip: 'Long open jobs — technician follow up.',
    },
  ),
  item(
    'REPORTS — Delivery Report',
    'REPORTS — Delivery Report',
    {
      what: 'Delivery order tracking and fulfillment stats (if DELIVERY enabled).',
      when: 'Review courier performance or pending deliveries.',
      open: 'Sidebar → Reports & Analytics → Delivery.',
      use: 'Filter status → see pending vs delivered orders.',
      tip: 'Link with Delivery Orders page for day-to-day updates.',
    },
    {
      what: 'Delivery tracking stats (enabled නම්).',
      when: 'Courier performance, pending deliveries.',
      open: 'Sidebar → Reports → Delivery.',
      use: 'Status filter → pending/delivered.',
      tip: 'Delivery Orders page daily updates.',
    },
  ),
  item(
    'REPORTS — Daily Reload Report',
    'REPORTS — Daily Reload Report',
    {
      what: 'Mobile reload/top-up sales summary (if DAILY_RELOAD enabled).',
      when: 'End of day reload counter reconciliation.',
      open: 'Sidebar → Reports & Analytics → Daily Reload Report.',
      use: 'Pick date → compare reload sales vs provider balance.',
      tip: 'Also use Daily Reload page for live sales entry.',
    },
    {
      what: 'Reload/top-up sales summary (enabled නම්).',
      when: 'Day end reload reconcile.',
      open: 'Sidebar → Daily Reload Report.',
      use: 'Date → sales vs provider balance.',
      tip: 'Daily Reload page live entry.',
    },
  ),
  item(
    'REPORTS — Recharge Card Report',
    'REPORTS — Recharge Card Report',
    {
      what: 'Recharge card sales report (if DAILY_RELOAD enabled).',
      when: 'Track physical recharge card sales separately from direct reload.',
      open: 'Sidebar → Reports & Analytics → Recharge Card Report.',
      use: 'Set date range → review card sales totals.',
      tip: 'Stock recharge cards like inventory if you track card serials.',
    },
    {
      what: 'Recharge card sales report (enabled නම්).',
      when: 'Physical card sales track.',
      open: 'Sidebar → Recharge Card Report.',
      use: 'Date range → totals review.',
      tip: 'Card serials inventory track.',
    },
  ),
  item(
    'REPORTS — Category Report',
    'REPORTS — Category Report',
    {
      what: 'Sales grouped by product category — phones, accessories, parts.',
      when: 'See which category drives revenue.',
      open: 'Sidebar → Reports & Analytics → Category Report (or dashboard link).',
      use: 'Pick period → compare category totals.',
      tip: 'Use when ordering stock — buy more of top categories.',
    },
    {
      what: 'Sales by product category.',
      when: 'Which category revenue drive.',
      open: 'Sidebar → Category Report.',
      use: 'Period → category totals compare.',
      tip: 'Stock order — top categories buy more.',
    },
  ),
  item(
    'REPORTS — Customer Report',
    'REPORTS — Customer Report',
    {
      what: 'Customer purchase history and top buyers.',
      when: 'Find VIP customers or credit exposure.',
      open: 'Sidebar → Reports & Analytics → Customer Report.',
      use: 'Sort by total spend or outstanding → export list.',
      tip: 'Cross-check high outstanding with Customers page before more credit.',
    },
    {
      what: 'Customer purchase history, top buyers.',
      when: 'VIP customers, credit exposure.',
      open: 'Sidebar → Customer Report.',
      use: 'Spend/outstanding sort → export.',
      tip: 'High outstanding — more credit නොදෙන්න.',
    },
  ),
  item(
    'REPORTS — Payment Methods',
    'REPORTS — Payment Methods',
    {
      what: 'Breakdown of sales by Cash, Card, UPI, Credit, etc.',
      when: 'Reconcile card terminal or check cash vs card mix.',
      open: 'Sidebar → Reports & Analytics → Payment Methods.',
      use: 'Pick date → see totals per payment type.',
      tip: 'Card total should match bank deposit — investigate gaps.',
    },
    {
      what: 'Sales by Cash, Card, UPI, Credit.',
      when: 'Card terminal reconcile, payment mix.',
      open: 'Sidebar → Payment Methods.',
      use: 'Date → payment type totals.',
      tip: 'Card total bank deposit match.',
    },
  ),
  item(
    'REPORTS — Purchase Report',
    'REPORTS — Purchase Report',
    {
      what: 'Purchases from suppliers — PO totals and receiving history.',
      when: 'Review buying patterns or supplier spend.',
      open: 'Sidebar → Reports & Analytics → Purchase Report.',
      use: 'Filter supplier/date → see purchase totals.',
      tip: 'Compare with Supplier Payments — bought vs paid should make sense.',
    },
    {
      what: 'Supplier purchases — PO totals, receive history.',
      when: 'Buying patterns, supplier spend.',
      open: 'Sidebar → Purchase Report.',
      use: 'Supplier/date filter → totals.',
      tip: 'Supplier Payments — bought vs paid compare.',
    },
  ),

  // ── HR, Delivery, Messaging, Reload ──
  item(
    'HR & STAFF — Staff & Roles',
    'HR & STAFF — Staff & Roles',
    {
      what: 'Add staff users, assign roles (Owner/Manager/Cashier/Technician), set permissions.',
      when: 'New employee joins or role changes.',
      open: 'Sidebar → HR & Staff → Staff & Roles.',
      use: 'Add Staff → credentials + role + branch → Permission Matrix tab to Hide/View/Edit per module.',
      tip: 'Cashier should not have Settings Edit — use matrix to restrict.',
    },
    {
      what: 'Staff add, roles, permissions.',
      when: 'New employee, role change.',
      open: 'Sidebar → Staff & Roles.',
      use: 'Add Staff → role + branch → Permission Matrix.',
      tip: 'Cashier Settings Edit නොදෙන්න — matrix restrict.',
    },
  ),
  // ── Wholesale ──
  item(
    'WHOLESALE — Dashboard',
    'WHOLESALE — Dashboard',
    {
      what: 'B2B wholesale home — dealer counts, open orders, shortcuts into wholesale workflows.',
      when: 'You sell accessories/phones to dealers (not walk-in retail). Feature WHOLESALE must be on.',
      open: 'Sidebar → Wholesale → Dashboard.',
      use: 'Check KPIs → jump to Dealers, POS, Orders, or Collections from shortcuts.',
      tip: 'Retail POS and Wholesale POS are separate — wholesale never creates a retail Sale.',
    },
    {
      what: 'B2B wholesale home — dealers, orders summary.',
      when: 'Dealers වලට තොග විකුණන shops (WHOLESALE enabled).',
      open: 'Sidebar → Wholesale → Dashboard.',
      use: 'KPIs බලලා Dealers / POS / Orders open.',
      tip: 'Retail POS සහ Wholesale POS වෙනම — retail Sale create වෙන්නේ නැහැ.',
    },
  ),
  item(
    'WHOLESALE — Wholesale POS',
    'WHOLESALE — Wholesale POS',
    {
      what: 'Counter checkout for a selected dealer — cash or credit wholesale invoice.',
      when: 'Dealer walks into the counter to buy stock today.',
      open: 'Sidebar → Wholesale → Wholesale POS.',
      use: 'Select dealer → add products → payments → Checkout → thermal print.',
      tip: 'Price comes from wholesale pricing (tier / list / product wholesale price).',
    },
    {
      what: 'Dealer counter checkout — wholesale invoice.',
      when: 'Dealer counter එකට එනකොට.',
      open: 'Wholesale → Wholesale POS.',
      use: 'Dealer → products → payment → Checkout.',
      tip: 'Price wholesale pricing එකෙන් resolve වෙනවා.',
    },
  ),
  item(
    'WHOLESALE — Dealers',
    'WHOLESALE — Dealers',
    {
      what: 'B2B dealer accounts — credit limit, outstanding, Approve / Hold / Suspend.',
      when: 'Onboard a new dealer or check who owes money.',
      open: 'Sidebar → Wholesale → Dealers.',
      use: 'New dealer → save → click code to open detail modal → Approve/Hold/Suspend or jump to Collections.',
      tip: 'Primary column opens the same style detail modal as Customers / Sales.',
    },
    {
      what: 'Dealer accounts — credit, outstanding, status.',
      when: 'New dealer / outstanding check.',
      open: 'Wholesale → Dealers.',
      use: 'New → code click → detail modal → Approve/Hold හෝ Collections.',
      tip: 'Detail modal Customers/Sales වගේ.',
    },
  ),
  item(
    'WHOLESALE — Pricing',
    'WHOLESALE — Pricing',
    {
      what: 'Dealer tiers and price lists that set wholesale unit prices.',
      when: 'Before first wholesale sale — set dealer tier pricing.',
      open: 'Sidebar → Wholesale → Pricing.',
      use: 'Create tier / price list → assign products → dealers use tier for resolve price.',
      tip: 'Without a list, system can fall back to product wholesale price.',
    },
    {
      what: 'Dealer tiers / price lists.',
      when: 'First wholesale sale එකට පෙර.',
      open: 'Wholesale → Pricing.',
      use: 'Tier / list create → products.',
      tip: 'List නැත්නම් product wholesale price use වෙන්න පුළුවන්.',
    },
  ),
  item(
    'WHOLESALE — Quotations & Orders',
    'WHOLESALE — Quotations & Orders',
    {
      what: 'Dealer quotes and delivery-channel sales orders with stock reserve on confirm.',
      when: 'Dealer wants a quote first, or you need warehouse fulfilment (not counter cash-and-carry).',
      open: 'Wholesale → Quotations / Orders.',
      use: 'New quote/order with catalog product → Issue/Accept → Submit/Confirm → click # to see lines in detail modal.',
      tip: 'Orders need productId for Confirm/reserve — pick from product search, not description-only.',
    },
    {
      what: 'Quotes සහ sales orders — confirm එකේ stock reserve.',
      when: 'Quote ඕන හෝ warehouse fulfilment.',
      open: 'Wholesale → Quotations / Orders.',
      use: 'Product select → Issue/Accept → Submit/Confirm → # click detail.',
      tip: 'Confirm එකට catalog product අනිවාර්ය.',
    },
  ),
  item(
    'WHOLESALE — Warehouse & Delivery',
    'WHOLESALE — Warehouse & Delivery',
    {
      what: 'Pick → pack → dispatch note → delivery trip with Arrive / POD.',
      when: 'After an order is Confirmed and must leave the warehouse.',
      open: 'Wholesale → Warehouse / Delivery.',
      use: 'Create pick → Pick all → Complete → Pack → Create DN → Confirm → New trip → Start → Arrive → POD.',
      tip: 'Open Pick # / DN # / Trip # for full lines and actions in the view modal.',
    },
    {
      what: 'Pick → pack → dispatch → trip POD.',
      when: 'Confirmed order warehouse එකෙන් යවනකොට.',
      open: 'Wholesale → Warehouse / Delivery.',
      use: 'Pick all → Complete → Pack → DN → Trip → Arrive → POD.',
      tip: 'Pick/DN/Trip # click → view modal.',
    },
  ),
  item(
    'WHOLESALE — Rep / Van Sales',
    'WHOLESALE — Rep / Van Sales',
    {
      what: 'Vehicles, reps, load stock, van sale, settlements — field distribution.',
      when: 'Reps sell from a van with allocated stock (needs REP_VAN_SALES).',
      open: 'Wholesale → Rep / Van Sales (or phone /rep / Flutter Hexalyte Rep).',
      use: 'Add vehicle → Assign rep → Load stock → Van sale → New settlement → Submit/Approve.',
      tip: 'Vehicle has its own stock branch — load before field day.',
    },
    {
      what: 'Van, reps, load, van sale, settlement.',
      when: 'Field reps van එකෙන් sell (REP_VAN_SALES).',
      open: 'Wholesale → Rep / Van හෝ /rep / Flutter app.',
      use: 'Vehicle → rep → Load → Van sale → Settlement.',
      tip: 'Load stock කලින් — vehicle stock branch.',
    },
  ),
  item(
    'WHOLESALE — Returns, Collections, Reports',
    'WHOLESALE — Returns, Collections, Reports',
    {
      what: 'Dealer RMA, AR collections/statement, and wholesale channel reports.',
      when: 'Dealer returns goods, pays outstanding, or you review Counter/Van/Delivery sales.',
      open: 'Wholesale → Returns / Collections / Reports.',
      use: 'RMA flow in detail modal; Collections → payment/task/statement; Reports → channel KPIs.',
      tip: 'From dealer detail, jump to Collections with ?dealerId= prefilled.',
    },
    {
      what: 'RMA, collections/statement, channel reports.',
      when: 'Return, outstanding collect, channel review.',
      open: 'Wholesale → Returns / Collections / Reports.',
      use: 'RMA detail → Collections payment/statement → Reports.',
      tip: 'Dealer detail එකෙන් Collections open.',
    },
  ),
  item(
    'DELIVERY — Delivery Orders',
    'DELIVERY — Delivery Orders',
    {
      what: 'Track sold items sent by courier — pending, out for delivery, delivered.',
      when: 'Customer buys phone but takes delivery later or by courier.',
      open: 'Sidebar → Delivery → Delivery Orders (if DELIVERY enabled).',
      use: 'Create from sale or manually → update status as courier progresses.',
      tip: 'Update status same day — customers call shop asking where phone is.',
    },
    {
      what: 'Courier delivery tracking (enabled නම්).',
      when: 'Later delivery / courier send.',
      open: 'Sidebar → Delivery Orders.',
      use: 'Order create → status update.',
      tip: 'Same day status update — customer calls reduce.',
    },
  ),
  item(
    'MESSAGING — WhatsApp',
    'MESSAGING — WhatsApp',
    {
      what: 'Connect shop WhatsApp to send invoices and messages to customers.',
      when: 'After sale — send PDF bill; marketing messages if shop uses them.',
      open: 'Sidebar → Messaging → WhatsApp.',
      use: 'Scan QR to connect → after POS sale click Send WhatsApp on success screen.',
      tip: 'Phone must stay online — disconnected WhatsApp stops sending.',
    },
    {
      what: 'Shop WhatsApp connect — invoice/message send.',
      when: 'Sale පස්සේ bill send.',
      open: 'Sidebar → WhatsApp.',
      use: 'QR connect → sale success Send WhatsApp.',
      tip: 'Phone online — disconnect නම් send නැහැ.',
    },
  ),
  item(
    'RELOAD — Daily Reload',
    'RELOAD — Daily Reload',
    {
      what: 'Sell mobile reload/top-up and record daily reload counter (if DAILY_RELOAD enabled).',
      when: 'Shop sells Dialog/Mobitel/Hutch reload.',
      open: 'Sidebar → Reload → Daily Reload.',
      use: 'Enter reload sales through the day → reconcile with Daily Reload Report at close.',
      tip: 'Mismatch with provider balance means missed entry or wrong amount typed.',
    },
    {
      what: 'Mobile reload/top-up sales (enabled නම්).',
      when: 'Reload counter shop.',
      open: 'Sidebar → Daily Reload.',
      use: 'Day reload entry → report reconcile.',
      tip: 'Provider balance mismatch — missed entry check.',
    },
  ),

  // ── System ──
  item(
    'SYSTEM — User Manual',
    'SYSTEM — User Manual',
    {
      what: 'This guide — how to use every part of Hexalyte for your shop.',
      when: 'Training new staff or refreshing on a module you rarely use.',
      open: 'Sidebar → System → User Manual.',
      use: 'Pick topic on left → read step-by-step on right → switch English / Sinhala / both.',
      tip: 'Start with Sidebar Map (this section) then POS for new cashiers.',
    },
    {
      what: 'මේ guide — Hexalyte use කරන හැටි.',
      when: 'New staff training, module refresh.',
      open: 'Sidebar → User Manual.',
      use: 'Topic select → step-by-step read → language switch.',
      tip: 'New cashiers — Sidebar Map then POS.',
    },
  ),
  item(
    'SYSTEM — Release Notes',
    'SYSTEM — Release Notes',
    {
      what: 'What is new in recent app updates — features and fixes.',
      when: 'After update notification or when something looks different in UI.',
      open: 'Sidebar → System → Release Notes.',
      use: 'Read latest entries → learn new buttons or changed flows.',
      tip: 'Hidden during Shop Quest onboarding so new users are not distracted.',
    },
    {
      what: 'නව updates — features, fixes.',
      when: 'Update පස්සේ UI change.',
      open: 'Sidebar → Release Notes.',
      use: 'Latest entries read.',
      tip: 'Shop Quest open වෙලාවේ hide.',
    },
  ),
  item(
    'SYSTEM — Feature Suggestions',
    'SYSTEM — Feature Suggestions',
    {
      what: 'Send ideas to Hexalyte team — request new features or improvements.',
      when: 'Shop needs something the app does not do yet.',
      open: 'Sidebar → System → Feature Suggestions.',
      use: 'Submit suggestion with clear description → track replies via notification badge.',
      tip: 'Include your shop type (mobile/repair) so team understands context.',
    },
    {
      what: 'Hexalyte team ට feature ideas send.',
      when: 'App එකේ නැති feature ඕන.',
      open: 'Sidebar → Feature Suggestions.',
      use: 'Suggestion submit → reply notification.',
      tip: 'Shop type (mobile/repair) mention.',
    },
  ),
  item(
    'SYSTEM — Branches',
    'SYSTEM — Branches',
    {
      what: 'Add and manage shop branches — multi-location businesses.',
      when: 'Opening a second shop or editing branch details.',
      open: 'Sidebar → System → Branches.',
      use: 'Add Branch → name, address → assign staff to branches in Staff & Roles.',
      tip: 'Each branch has separate stock — use Stock Transfer between them.',
    },
    {
      what: 'Shop branches manage — multi-location.',
      when: 'Second shop open, branch edit.',
      open: 'Sidebar → Branches.',
      use: 'Add Branch → staff assign.',
      tip: 'Branch stock separate — Stock Transfer use.',
    },
  ),
  item(
    'SYSTEM — Settings',
    'SYSTEM — Settings',
    {
      what: 'Shop configuration — info, invoice format, features, integrations.',
      when: 'Setup new shop, change bill layout, enable/disable modules.',
      open: 'Sidebar → System → Settings.',
      use: 'Tabs: Shop Info, Invoice, Features, etc. → change → Save → test in POS.',
      tip: 'Shop Quest Mission often ends here — invoice logo and auto-print setup.',
    },
    {
      what: 'Shop config — info, invoice, features.',
      when: 'New shop setup, bill change, modules enable.',
      open: 'Sidebar → Settings.',
      use: 'Tabs → change → Save → POS test.',
      tip: 'Shop Quest — invoice logo, auto-print.',
    },
  ),
]
