import { SIDEBAR_GUIDE_STEP_GROUPS } from './sidebarGuideStepGroups'

export type ManualLang = 'en' | 'si' | 'both'

/** Numbered step block — shown when a section is opened on its own. */
export type ManualStepGroup = {
  titleEn: string
  titleSi: string
  stepsEn: string[]
  stepsSi: string[]
}

export interface ManualSection {
  id: string
  icon?: string
  titleEn: string
  titleSi: string
  /** Optional intro bullets (tips / reference). */
  itemsEn: string[]
  itemsSi: string[]
  /** Step-by-step setup — primary content when present. */
  stepGroups?: ManualStepGroup[]
}

export const USER_MANUAL_SECTIONS: ManualSection[] = [
  {
    id: 'start',
    titleEn: 'Getting Started',
    titleSi: 'පටන් ගැනීම',
    itemsEn: [
      'Open your shop URL and sign in with the email and password from your owner.',
      'New shop owners can register at the Register page — 14-day trial starts automatically.',
      'Complete Settings → Shop Info (name, phone, address) and Settings → Invoice (logo, bill format).',
      'Forgot password? Use the link on the login page to reset via email.',
    ],
    itemsSi: [
      'Shop URL open කර owner දුන් email/password එකෙන් login වන්න.',
      'නව owners Register page එකෙන් shop register කරන්න — 14-day trial start වෙනවා.',
      'Settings → Shop Info (name, phone, address) සහ Settings → Invoice (logo, bill) complete කරන්න.',
      'Password forgot? Login page → Forgot password → email link.',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Login & first look',
        titleSi: 'Step 1 — Login & first look',
        stepsEn: [
          'Open your shop link (e.g. app.hexalyte.com or your shop subdomain).',
          'Enter email + password from your owner → Sign in.',
          'Check the Dashboard — today sales, alerts, shortcuts.',
          'Top bar: select your Branch if you have more than one.',
        ],
        stepsSi: [
          'Shop link open (app.hexalyte.com හෝ shop subdomain).',
          'Owner දුන් email + password → Sign in.',
          'Dashboard බලන්න — sales, alerts, shortcuts.',
          'Header එකේ Branch select (branches කිහිපයක් නම්).',
        ],
      },
      {
        titleEn: 'Step 2 — Shop Info setup',
        titleSi: 'Step 2 — Shop Info setup',
        stepsEn: [
          'Sidebar → Settings.',
          'Open Shop Info tab.',
          'Fill shop name, phone, address, email — these print on bills.',
          'Save changes.',
        ],
        stepsSi: [
          'Sidebar → Settings.',
          'Shop Info tab open.',
          'Shop name, phone, address, email fill — bills වල print වෙනවා.',
          'Save.',
        ],
      },
      {
        titleEn: 'Step 3 — Invoice & bill setup',
        titleSi: 'Step 3 — Invoice & bill setup',
        stepsEn: [
          'Settings → Invoice tab.',
          'Upload shop logo (optional).',
          'Choose print format: Thermal 58mm, 80mm, or Stock Form.',
          'Set warranty terms and bill footer text if needed.',
          'Turn on POS auto-print if you want bills to print after every sale.',
          'Save.',
        ],
        stepsSi: [
          'Settings → Invoice tab.',
          'Logo upload (optional).',
          'Print format select: Thermal 58mm / 80mm / Stock Form.',
          'Warranty terms, bill footer set.',
          'POS auto-print on/off.',
          'Save.',
        ],
      },
      {
        titleEn: 'Step 4 — Staff & permissions (Owner)',
        titleSi: 'Step 4 — Staff & permissions (Owner)',
        stepsEn: [
          'Sidebar → Staff & Roles.',
          'Click Add Staff — name, email, password, role (Cashier/Technician/Manager).',
          'Assign at least one branch.',
          'Open Permission Matrix — set Hide / View / Edit per module for each role.',
          'Save matrix.',
        ],
        stepsSi: [
          'Sidebar → Staff & Roles.',
          'Add Staff — name, email, password, role.',
          'Branch assign.',
          'Permission Matrix — Hide / View / Edit set.',
          'Save.',
        ],
      },
    ],
  },
  {
    id: 'sidebar-guide',
    titleEn: 'Sidebar — Full System Map',
    titleSi: 'Sidebar — සම්පූර්ණ System Map',
    itemsEn: [
      'Each block below matches one sidebar menu item — what it is, when to use it, and how.',
      'Items appear only if your plan and role allow them (locked items unlock via Shop Quest for trial shops).',
      'HEADER: Branch selector + POS Terminal (F2) — top bar, not in the left sidebar.',
      'Scroll down through numbered sections — OVERVIEW, SALES, INVENTORY, SERVICE, FINANCE, REPORTS, HR, DELIVERY, MESSAGING, RELOAD, SYSTEM.',
      'For deep guides on POS, Repairs, HP, Accounting — open those topics in the left manual list.',
    ],
    itemsSi: [
      'යට blocks එක් එක sidebar menu item එකක් — මොකක්ද, කවදා use, කොහොම use.',
      'Plan සහ role අනුව items පෙන්වනවා (trial shops Shop Quest unlock).',
      'HEADER: Branch + POS Terminal (F2) — top bar.',
      'Numbered sections scroll — OVERVIEW, SALES, INVENTORY, SERVICE, FINANCE, REPORTS, HR, DELIVERY, MESSAGING, RELOAD, SYSTEM.',
      'POS, Repairs, HP, Accounting deep guides — manual left list එකෙන් open.',
    ],
    stepGroups: SIDEBAR_GUIDE_STEP_GROUPS,
  },
  {
    id: 'pos',
    titleEn: 'Point of Sale (POS)',
    titleSi: 'POS — විකිණීම',
    itemsEn: [
      'Open POS from the sidebar (Point of Sale).',
      'Add products: click a product, search by name/SKU, or scan IMEI barcode for tracked phones.',
      'Select customer (F2) — required for warranty products and credit sales.',
      'Edit price: click the price line under each cart item → Save.',
      'Edit warranty: click the warranty badge → pick period → optional note → Save.',
      'Checkout (F9): choose Cash, Card, or UPI. Enter cash received for change calculation.',
      'Credit sale: select customer first — unpaid amount adds to their outstanding balance.',
      'After sale: reprint (F5), download PDF, or send WhatsApp invoice if connected.',
    ],
    itemsSi: [
      'Sidebar → Point of Sale open කරන්න.',
      'Products: click, search, හෝ IMEI scan කරන්න.',
      'Customer select (F2) — warranty සහ credit sales සඳහා අනිවාර්ය.',
      'Price edit: cart item යට price line click → Save.',
      'Warranty edit: warranty badge click → period + note → Save.',
      'Checkout (F9): Cash / Card / UPI. Cash received දාන්න change සඳහා.',
      'Credit sale: customer select → due balance customer account එකට.',
      'Sale එකට පස්සේ: F5 reprint, PDF, WhatsApp invoice.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — one sale',
        titleSi: 'Step-by-step — එක sale',
        stepsEn: [
          'Sidebar → Point of Sale (or header POS Terminal / F2).',
          'Add products: click tile, search name/SKU, or scan IMEI barcode.',
          'Press F2 → search customer by phone (required for warranty & credit).',
          'Edit price if needed: click price under item → change → Save.',
          'Edit warranty if needed: click warranty badge → months + note → Save.',
          'Press F9 (Checkout) → pick Cash / Card / UPI / Credit.',
          'Cash: enter amount received → system shows change.',
          'Complete sale → bill prints (if auto-print on). F5 reprint if needed.',
          'F10 → clear cart for next customer.',
        ],
        stepsSi: [
          'Sidebar → Point of Sale (හෝ F2).',
          'Products add: click, search, IMEI scan.',
          'F2 → customer search (warranty/credit සඳහා).',
          'Price edit: item යට price → Save.',
          'Warranty edit: badge → months → Save.',
          'F9 Checkout → Cash/Card/UPI/Credit.',
          'Cash: received amount → change.',
          'Sale complete → bill print. F5 reprint.',
          'F10 → next customer.',
        ],
      },
    ],
  },
  {
    id: 'pos-keys',
    titleEn: 'POS Keyboard Shortcuts',
    titleSi: 'POS Keyboard Shortcuts',
    itemsEn: [
      'F2 — Customer search',
      'F3 / Ctrl+Enter — Pay now',
      'F4 — Hold cart',
      'F5 — Reprint last bill',
      'F9 — Checkout',
      'F10 — New sale (clear cart)',
      'F11 — Day end / daily closing',
      'F12 — Calculator',
    ],
    itemsSi: [
      'F2 — Customer search',
      'F3 / Ctrl+Enter — Pay now',
      'F4 — Cart hold',
      'F5 — Bill reprint',
      'F9 — Checkout',
      'F10 — New sale',
      'F11 — Day end',
      'F12 — Calculator',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — learn POS keys',
        titleSi: 'Step-by-step — POS keys',
        stepsEn: [
          'Open POS from sidebar or press F2 from anywhere in the dashboard.',
          'Press F2 — customer search opens (use before warranty or credit sale).',
          'Add products to cart, then press F9 for Checkout.',
          'Press F3 or Ctrl+Enter for quick Pay Now if your shop uses it.',
          'Press F4 to Hold cart when customer steps away.',
          'After sale: F5 reprints the last bill.',
          'Press F10 to clear cart and start a new sale.',
          'At day end: F11 opens Daily Closing.',
          'Press F12 for built-in calculator.',
        ],
        stepsSi: [
          'Sidebar → POS (හෝ F2).',
          'F2 — customer search.',
          'Products add → F9 Checkout.',
          'F3 / Ctrl+Enter — Pay Now (use නම්).',
          'F4 — cart hold.',
          'Sale එකට පස්සේ F5 — bill reprint.',
          'F10 — new sale, cart clear.',
          'Day end F11 — Daily Closing.',
          'F12 — calculator.',
        ],
      },
    ],
  },
  {
    id: 'inventory',
    titleEn: 'Inventory & Products',
    titleSi: 'Inventory & Products',
    itemsEn: [
      'Inventory page — view all products, stock levels, and product details.',
      'Add Product — set name, brand, category, prices, stock, warranty period, warranty note, IMEI tracking, and variants.',
      'Import CSV — download template, fill in Excel, upload for bulk import.',
      'Add Stock — receive stock for existing products without creating a new product.',
      'Warranty note on a product prints on the stock-form bill under that line item.',
    ],
    itemsSi: [
      'Inventory — products, stock, details බලන්න.',
      'Add Product — name, brand, category, price, stock, warranty, IMEI, variants.',
      'CSV Import — template download → fill → upload.',
      'Add Stock — existing product එකට stock add.',
      'Product warranty note stock-form bill එකේ item යට print වෙනවා.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Add new product',
        titleSi: 'Step-by-step — Product add',
        stepsEn: [
          'Sidebar → Inventory → Add Product.',
          'Name, brand, category — fill basic details.',
          'Selling price + cost price (cost visible to Owner/Manager only).',
          'Opening stock qty for this branch.',
          'Warranty months + note if applicable.',
          'Enable IMEI tracking for phones — each unit gets unique IMEI.',
          'Add variants (colour/storage) if product has options.',
          'Save — product appears in Inventory list and POS.',
        ],
        stepsSi: [
          'Sidebar → Inventory → Add Product.',
          'Name, brand, category fill.',
          'Selling price + cost price.',
          'Opening stock qty.',
          'Warranty months + note.',
          'IMEI tracking on (phones).',
          'Variants add (optional).',
          'Save → Inventory + POS.',
        ],
      },
      {
        titleEn: 'Step-by-step — Add stock to existing product',
        titleSi: 'Step-by-step — Stock add',
        stepsEn: [
          'Inventory → find product → click Add Stock (or row action).',
          'Enter quantity received.',
          'For IMEI products: enter each IMEI number.',
          'Save — stock increases for active branch.',
        ],
        stepsSi: [
          'Inventory → product find → Add Stock.',
          'Qty enter.',
          'IMEI products: each IMEI enter.',
          'Save — stock increase.',
        ],
      },
    ],
  },
  {
    id: 'customers',
    titleEn: 'Customers',
    titleSi: 'Customers',
    itemsEn: [
      'Add and search customers with name, phone, and address.',
      'Outstanding balance is tracked for credit customers.',
      'Collect old outstanding balance from POS checkout when customer is selected.',
    ],
    itemsSi: [
      'Customers add/search — name, phone, address.',
      'Credit customers outstanding balance track වෙනවා.',
      'POS checkout එකේ පරණ outstanding collect කරන්න පුළුවන්.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Add customer',
        titleSi: 'Step-by-step — Customer add',
        stepsEn: [
          'Sidebar → Customers.',
          'Click Add Customer (or + button).',
          'Enter name and phone (phone is used for quick search in POS).',
          'Add address if you deliver or need it on bills.',
          'Save — customer appears in search when you press F2 in POS.',
        ],
        stepsSi: [
          'Sidebar → Customers.',
          'Add Customer click.',
          'Name + phone enter (POS F2 search).',
          'Address (optional).',
          'Save → POS F2 search එකේ පෙන්වනවා.',
        ],
      },
      {
        titleEn: 'Step-by-step — Credit & collect outstanding',
        titleSi: 'Step-by-step — Credit & outstanding',
        stepsEn: [
          'In POS press F2 and select the credit customer.',
          'Complete sale with Credit payment — unpaid amount adds to outstanding.',
          'Next visit: select same customer in POS checkout.',
          'Collect old outstanding as part of payment before or with new sale.',
          'Check Customers page for full outstanding balance list.',
        ],
        stepsSi: [
          'POS F2 → credit customer select.',
          'Credit payment → outstanding increase.',
          'Next visit POS checkout → same customer.',
          'පරණ outstanding collect.',
          'Customers page — balance list.',
        ],
      },
    ],
  },
  {
    id: 'sales-returns',
    titleEn: 'Sales & Returns',
    titleSi: 'Sales & Returns',
    itemsEn: [
      'Sales History — view all invoices, search, reprint bills.',
      'Returns — find original sale, select items to return; stock and IMEI are restored automatically.',
    ],
    itemsSi: [
      'Sales History — invoices, reprint.',
      'Returns — original sale → items return → stock restore.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Reprint an invoice',
        titleSi: 'Step-by-step — Invoice reprint',
        stepsEn: [
          'Sidebar → Sales History.',
          'Search by invoice number, customer phone, or date.',
          'Click the invoice row to open details.',
          'Click Reprint or Download PDF.',
          'In POS you can also press F5 for the last bill only.',
        ],
        stepsSi: [
          'Sidebar → Sales History.',
          'Invoice no / phone / date search.',
          'Row click → details open.',
          'Reprint / PDF download.',
          'POS F5 — last bill only.',
        ],
      },
      {
        titleEn: 'Step-by-step — Process a return',
        titleSi: 'Step-by-step — Return process',
        stepsEn: [
          'Sidebar → Returns.',
          'Find the original sale (invoice no or customer).',
          'Select items and quantities to return.',
          'Confirm return — stock and IMEI restore automatically.',
          'Refund or adjust payment as your shop policy requires.',
        ],
        stepsSi: [
          'Sidebar → Returns.',
          'Original sale find.',
          'Return items + qty select.',
          'Confirm — stock/IMEI auto restore.',
          'Refund/adjust payment.',
        ],
      },
    ],
  },
  {
    id: 'repairs',
    titleEn: 'Repair Jobs — Advanced Guide',
    titleSi: 'Repair Jobs — Advanced Guide',
    itemsEn: [
      'Sidebar → Repair Jobs. Needs REPAIRS permission (Owner/Manager/Technician by default; Cashier usually hidden).',
      'WHAT IT DOES: Track phones/devices from intake → repair → ready → payment → delivered. Each job gets a ticket number.',
      'STEP 1 — NEW TICKET: Click New Repair. Customer (search or add), device brand/model, IMEI, accessories, phone condition, fault (multi-select), technician, priority, estimated completion date.',
      'After save: Device Intake slip prints automatically (thermal) — customer signs; keep a copy. Allow browser pop-ups if print fails.',
      'STEP 2 — WORK ON JOB: Open ticket from list. Progress bar shows: Received → In Repair → Ready. Click "Move to next status" as work advances.',
      'Set EST. COST (service/labour quote) — this is what the customer pays. Edit inline on the detail screen.',
      'STEP 3 — SPARE PARTS (optional): Search inventory, add parts used (screen, battery, etc.). Parts are for YOUR internal profit tracking — customer bill is the service quote, not parts added on top.',
      'Stock is checked when adding parts; stock deducts when payment is collected, not when part is added.',
      'Parts & Profit panel (Owner/Manager only): shows labour share, parts margin, net profit after discount.',
      'STEP 4 — READY: Move status to Ready when repair is done. Customer can collect. Send WhatsApp quote from detail screen if WhatsApp is connected.',
      'STEP 5 — COLLECT PAYMENT: At Ready, click Collect Payment. Enter discount (if any), payment method (Cash/Card/Cheque/etc.), partial pay + credit if enabled.',
      'On confirm: job becomes Delivered, sale appears in Sales History, stock reduces, repair warranty registers if set.',
      'PRINTING: Intake slip (on create), Job Receipt (list/detail), A4 PDF download, WhatsApp quote/invoice with optional PDF.',
      'Toggle "Show parts on invoice" — parts listed for info only; customer total stays the service quote.',
      'NOTES & PHOTOS: Add technician notes (can print on invoice). Upload damage photos/PDF as attachments.',
      'WARRANTY: Set repair warranty months on ticket (1/3/6/12/24). Registers in Warranty page when job is paid. Can start from Warranty claim → Create repair.',
      'EDIT / CANCEL: Edit ticket until Delivered or Cancelled. Cancel job if customer does not proceed.',
      'LIST PAGE: Stat cards filter by status. Search ticket #, customer, IMEI. Double-click row to edit.',
      'REPORTS → Repairs tab: delivered jobs financial statement, parts cost, labour, CSV export.',
      'SETTINGS: Settings → Invoice — repair thermal width, intake terms, default repair warranty months.',
      'Daily flow tip: Intake + print slip → assign technician → add parts if needed → set quote → Ready → collect payment → delivered.',
    ],
    itemsSi: [
      'Sidebar → Repair Jobs. REPAIRS permission ඕන (Owner/Manager/Technician; Cashier usually hide).',
      'මොකද කරන්නේ: Phone/device intake → repair → ready → payment → delivered track. Ticket number එකක් assign වෙනවා.',
      'STEP 1 — NEW TICKET: New Repair click. Customer (search/add), device brand/model, IMEI, accessories, phone condition, fault select, technician, priority, estimated date.',
      'Save කරපු ගමන් Device Intake slip auto print (thermal) — customer sign. Pop-up block නම් allow කරන්න.',
      'STEP 2 — WORK ON JOB: List එකෙන් ticket open. Progress: Received → In Repair → Ready. "Move to next status" click කරන්න.',
      'EST. COST (service quote) set කරන්න — customer ගෙවන්නේ මේ amount. Detail screen එකේ edit කරන්න පුළුවන්.',
      'STEP 3 — SPARE PARTS (optional): Inventory search, parts add (screen, battery, etc.). Parts customer bill එකට add නෙමෙයි — internal profit track විතරක්.',
      'Part add කරනකොට stock check; stock reduce වෙන්නේ payment collect කරනකොට.',
      'Parts & Profit panel (Owner/Manager): labour share, parts margin, net profit.',
      'STEP 4 — READY: Repair ඉවර නම් Ready status. WhatsApp quote send කරන්න පුළුවන් (WhatsApp connected නම්).',
      'STEP 5 — COLLECT PAYMENT: Ready වෙද්දී Collect Payment. Discount, payment method, partial pay + credit (enabled නම්).',
      'Confirm කරපු ගමන් Delivered, Sales History එකේ sale, stock reduce, warranty register (set නම්).',
      'PRINTING: Intake slip, Job Receipt, A4 PDF, WhatsApp quote/invoice.',
      '"Show parts on invoice" toggle — parts info විතරක්; customer total = service quote.',
      'NOTES & PHOTOS: Technician notes add (invoice එකේ print වෙන්න පුළුවන්). Damage photos upload.',
      'WARRANTY: Ticket එකේ repair warranty months set (1/3/6/12/24). Payment collect කරනකොට Warranty page register. Warranty claim → repair start කරන්න පුළුවන්.',
      'EDIT / CANCEL: Delivered/Cancelled වෙනකම් edit. Cancel job — customer proceed නොකරනවා නම්.',
      'LIST PAGE: Stat cards status filter. Ticket #, customer, IMEI search. Row double-click → edit.',
      'REPORTS → Repairs: delivered jobs financial statement, parts cost, labour, CSV.',
      'SETTINGS: Settings → Invoice — repair thermal, intake terms, default warranty.',
      'Daily flow: Intake + slip → technician → parts → quote → Ready → payment → delivered.',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Create repair ticket (intake)',
        titleSi: 'Step 1 — Repair ticket create (intake)',
        stepsEn: [
          'Sidebar → Repair Jobs → click New Repair.',
          'Customer: search by phone/name or register new customer.',
          'Device: pick brand + model from catalog; enter IMEI if phone.',
          'Accessories: tick what customer left (charger, box, etc.).',
          'Phone condition: describe scratches, cracks, display issues.',
          'Fault: select from list (or add new fault); can pick multiple.',
          'Job: assign Technician, set Priority, estimated completion date.',
          'Click Save — ticket number is created.',
          'Device Intake slip prints — customer signs; keep your copy. (Allow pop-ups if blocked.)',
        ],
        stepsSi: [
          'Sidebar → Repair Jobs → New Repair.',
          'Customer: phone/name search හෝ new register.',
          'Device: brand + model; IMEI enter (phone නම්).',
          'Accessories: customer එක්ක තියෙන දේ tick.',
          'Phone condition: scratches, cracks, display describe.',
          'Fault: list එකෙන් select (multiple OK).',
          'Technician assign, Priority, estimated date.',
          'Save — ticket number create.',
          'Intake slip print — customer sign. Pop-up allow.',
        ],
      },
      {
        titleEn: 'Step 2 — Work on the repair',
        titleSi: 'Step 2 — Repair work',
        stepsEn: [
          'Click ticket from list to open detail view.',
          'Click Move to next status → In Repair when technician starts work.',
          'Set Est. Cost (service quote) — this is what customer will pay.',
          'Add technician notes if needed (visible on invoice optional).',
          'Upload damage photos in Attachments if useful.',
        ],
        stepsSi: [
          'List එකෙන් ticket open.',
          'Move to next status → In Repair.',
          'Est. Cost (service quote) set — customer pay amount.',
          'Technician notes add (optional).',
          'Damage photos upload (Attachments).',
        ],
      },
      {
        titleEn: 'Step 3 — Add spare parts (optional)',
        titleSi: 'Step 3 — Spare parts (optional)',
        stepsEn: [
          'In detail view → Items section → search product by name/SKU.',
          'Pick part, enter quantity → Add.',
          'System checks stock — must have enough in inventory.',
          'Parts are for your internal profit tracking — NOT added on top of customer bill.',
          'Owner/Manager can open Parts & Profit panel to see margin.',
        ],
        stepsSi: [
          'Detail → Items → product search.',
          'Part + qty → Add.',
          'Stock check — inventory එකේ තියෙන්න ඕන.',
          'Parts customer bill එකට add නෙමෙයි — internal profit track.',
          'Parts & Profit panel (Owner/Manager).',
        ],
      },
      {
        titleEn: 'Step 4 — Ready for pickup',
        titleSi: 'Step 4 — Ready',
        stepsEn: [
          'When repair finished → Move to next status → Ready.',
          'Optional: WhatsApp → send Quote to customer (needs WhatsApp connected).',
          'Optional: Print Job Receipt or Download PDF for customer.',
          'Set repair warranty months on ticket if you give service warranty.',
        ],
        stepsSi: [
          'Repair ඉවර → Ready status.',
          'WhatsApp Quote send (optional).',
          'Job Receipt / PDF (optional).',
          'Repair warranty months set (optional).',
        ],
      },
      {
        titleEn: 'Step 5 — Collect payment & deliver',
        titleSi: 'Step 5 — Payment & deliver',
        stepsEn: [
          'At Ready status → click Collect Payment.',
          'Enter discount if any — reduces customer total.',
          'Choose payment method: Cash, Card, Cheque, etc.',
          'Partial pay + credit: only if CUSTOMER_CREDIT feature enabled.',
          'Confirm — status becomes Delivered.',
          'Sale appears in Sales History; spare parts stock reduces; warranty registers if set.',
        ],
        stepsSi: [
          'Ready → Collect Payment.',
          'Discount enter (optional).',
          'Payment method select.',
          'Partial pay + credit (feature enabled නම්).',
          'Confirm → Delivered.',
          'Sales History sale, stock reduce, warranty register.',
        ],
      },
    ],
  },
  {
    id: 'warranty',
    titleEn: 'Warranty',
    titleSi: 'Warranty',
    itemsEn: [
      'Warranty certificates are created automatically on POS sale when product has warranty months and a customer is selected.',
      'Edit warranty period and note in POS cart before checkout (sale-specific).',
      'Warranty page — view certificates and process claims.',
      'Shop-wide warranty terms: Settings → Invoice → Warranty & Service Terms.',
    ],
    itemsSi: [
      'POS sale එකේ warranty auto create (customer + warranty product).',
      'POS cart එකේ warranty period/note edit කරන්න පුළුවන්.',
      'Warranty page — certificates, claims.',
      'Shop terms: Settings → Invoice → Warranty & Service Terms.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Warranty on sale',
        titleSi: 'Step-by-step — Sale warranty',
        stepsEn: [
          'Product must have warranty months > 0 in Inventory.',
          'In POS press F2 and select customer (required for warranty).',
          'Add product to cart — warranty badge shows default period.',
          'Click warranty badge to change months or add a note for this sale.',
          'Complete checkout — certificate creates automatically.',
        ],
        stepsSi: [
          'Product warranty months > 0.',
          'POS F2 → customer select.',
          'Product add → warranty badge.',
          'Badge click → months/note edit.',
          'Checkout → certificate auto create.',
        ],
      },
      {
        titleEn: 'Step-by-step — View & claims',
        titleSi: 'Step-by-step — View & claims',
        stepsEn: [
          'Sidebar → Warranty.',
          'Search certificate by customer phone or IMEI.',
          'Open certificate to see start/end date and product.',
          'Process claim if customer returns within warranty period.',
          'Shop-wide terms: Settings → Invoice → Warranty & Service Terms.',
        ],
        stepsSi: [
          'Sidebar → Warranty.',
          'Phone/IMEI search.',
          'Certificate open — dates check.',
          'Claim process (period ඇතුළත).',
          'Shop terms: Settings → Invoice.',
        ],
      },
    ],
  },
  {
    id: 'finance',
    titleEn: 'Finance & Daily Closing',
    titleSi: 'Finance & Daily Closing',
    itemsEn: [
      'Finance — income and expense summary by date.',
      'Expenses — record shop running costs.',
      'Daily Closing — count cash by denomination at end of day and close the business day.',
      'Profit Allocation — distribute profit to internal funds (if enabled).',
    ],
    itemsSi: [
      'Finance — income/expense summary.',
      'Expenses — shop expenses record.',
      'Daily Closing — day end cash count, day close.',
      'Profit Allocation — profit distribute (enabled නම්).',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Record expenses',
        titleSi: 'Step 1 — Expenses record',
        stepsEn: [
          'Sidebar → Finance → Expenses.',
          'Click Add Expense.',
          'Enter amount, category, and date (rent, utilities, etc.).',
          'Save — expense appears in Finance summary.',
        ],
        stepsSi: [
          'Sidebar → Finance → Expenses.',
          'Add Expense.',
          'Amount, category, date enter.',
          'Save → Finance summary.',
        ],
      },
      {
        titleEn: 'Step 2 — Review cash flow',
        titleSi: 'Step 2 — Cash flow review',
        stepsEn: [
          'Open Finance page for income vs expense by date.',
          'Open Profit & Loss for revenue vs cost report.',
          'Use date filters to compare days or months.',
        ],
        stepsSi: [
          'Finance page — income/expense by date.',
          'Profit & Loss — revenue vs cost.',
          'Date filter use.',
        ],
      },
      {
        titleEn: 'Step 3 — Daily closing (end of day)',
        titleSi: 'Step 3 — Daily closing',
        stepsEn: [
          'At shop close: Sidebar → Daily Closing (or press F11 in POS).',
          'Count cash by denomination in the drawer.',
          'Enter counted amounts — system compares with expected sales.',
          'Note any difference and close the business day.',
          'Next day starts fresh sales totals.',
        ],
        stepsSi: [
          'Shop close: Daily Closing (F11).',
          'Cash count by denomination.',
          'Counted amounts enter — expected vs actual.',
          'Difference note → day close.',
          'Next day fresh totals.',
        ],
      },
    ],
  },
  {
    id: 'hire-purchase',
    titleEn: 'Hire Purchase (HP)',
    titleSi: 'Hire Purchase (HP) — වාරික විකිණීම',
    itemsEn: [
      'Use when customers buy on installments (down payment + monthly dues) instead of full cash at POS.',
      'HP Dashboard — summary of active agreements, collections today, overdue amounts, and quick alerts.',
      'Agreements — create and view HP contracts: customer, product, down payment, monthly amount, duration, guarantor.',
      'Payment Collection — record installment payments when customer pays their monthly due.',
      'Due Collections — list of installments due today or this period — who to call/collect from.',
      'Defaulters — customers who missed payments or are overdue — follow up and track recovery.',
      'Guarantors — people who guarantee the HP agreement if the buyer defaults.',
      'HP Reports — collection reports, outstanding balance, agreement status.',
      'HP Settings — down payment rules, interest/penalty, agreement terms, numbering.',
      'Typical flow: Create agreement → customer pays down payment → collect monthly dues → close when fully paid.',
    ],
    itemsSi: [
      'Customer full cash නැතුව down payment + monthly installments ගෙවන විට use කරන්න.',
      'HP Dashboard — active agreements, අද collections, overdue, alerts summary.',
      'Agreements — HP contract create/view: customer, product, down payment, monthly amount, duration, guarantor.',
      'Payment Collection — customer monthly installment ගෙවනකොට payment record.',
      'Due Collections — අද/මේ period එකේ due installments — collect කරන්න ඕන list.',
      'Defaulters — payment miss / overdue customers — follow up.',
      'Guarantors — buyer default වුණොත් guarantee දෙන අය.',
      'HP Reports — collection, outstanding, agreement status reports.',
      'HP Settings — down payment rules, penalty, agreement terms, numbering.',
      'Flow: Agreement create → down payment → monthly collect → full paid වුණාම close.',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Before you start',
        titleSi: 'Step 1 — පටන් ගන්න කලින්',
        stepsEn: [
          'Confirm Hire Purchase feature is enabled for your shop (Settings → Features or plan).',
          'Open Finance → Hire Purchase → HP Settings.',
          'Set down payment rules, penalty/interest if used, agreement numbering.',
          'Save settings.',
        ],
        stepsSi: [
          'Hire Purchase feature enabled ද confirm.',
          'Finance → Hire Purchase → HP Settings.',
          'Down payment rules, penalty, numbering set.',
          'Save.',
        ],
      },
      {
        titleEn: 'Step 2 — Create HP agreement',
        titleSi: 'Step 2 — HP agreement create',
        stepsEn: [
          'Hire Purchase → Agreements → New Agreement.',
          'Select or add customer (name, phone, NIC if needed).',
          'Select product/device being sold on installments.',
          'Enter down payment amount customer pays today.',
          'Enter monthly installment amount and number of months.',
          'Add guarantor details if required.',
          'Review total and save agreement.',
          'Collect down payment (record in Payment Collection or linked flow).',
        ],
        stepsSi: [
          'Hire Purchase → Agreements → New.',
          'Customer select/add.',
          'Product select.',
          'Down payment amount.',
          'Monthly amount + months count.',
          'Guarantor (optional).',
          'Save agreement.',
          'Down payment collect/record.',
        ],
      },
      {
        titleEn: 'Step 3 — Monthly collection',
        titleSi: 'Step 3 — Monthly collection',
        stepsEn: [
          'Each month open Due Collections — see who must pay today/this period.',
          'When customer pays → Payment Collection → select agreement → enter amount.',
          'Receipt/record saves; balance reduces.',
          'Repeat until agreement fully paid.',
        ],
        stepsSi: [
          'Due Collections — අද due list බලන්න.',
          'Customer pay කරනකොට Payment Collection → agreement → amount.',
          'Balance reduce.',
          'Full paid වෙනකම් repeat.',
        ],
      },
      {
        titleEn: 'Step 4 — Follow up defaulters',
        titleSi: 'Step 4 — Defaulters follow up',
        stepsEn: [
          'Open Defaulters list for missed/overdue installments.',
          'Call customer or guarantor — note follow-up.',
          'Record partial payments when received.',
          'Use HP Reports for outstanding balance summary.',
        ],
        stepsSi: [
          'Defaulters list — missed payments.',
          'Customer/guarantor call — follow up.',
          'Partial payments record.',
          'HP Reports — outstanding summary.',
        ],
      },
    ],
  },
  {
    id: 'accounting',
    titleEn: 'Accounting (GL)',
    titleSi: 'Accounting — ගිණුම්කරණය',
    itemsEn: [
      'Full double-entry bookkeeping for the shop — not just daily sales summary. Enable only if you need proper accounts.',
      'Overview — chart of accounts snapshot, recent journal activity, key balances.',
      'GL Journals — manual journal entries (debit/credit) for adjustments, transfers, and corrections.',
      'GL Reports — trial balance, profit & loss, balance sheet from the general ledger.',
      'AR / AP — Accounts Receivable (customers owe you) and Accounts Payable (you owe suppliers).',
      'Cash & Bank — track cash drawers and bank accounts; reconcile deposits and withdrawals.',
      'VAT / Tax — tax-related entries and reports if your shop is VAT registered.',
      'Petty Cash — small daily cash expenses paid from a petty cash float.',
      'Payroll — staff salary records and payroll journals if you run payroll through the system.',
      'Periods — open/close accounting periods so past months cannot be changed accidentally.',
      'Audit Trail — log of who changed what in accounting (for control and review).',
      'Accounting Settings — fiscal year, default accounts, posting rules.',
      'Note: POS sales and supplier payments may auto-post to accounting when integration is enabled.',
    ],
    itemsSi: [
      'Shop එකේ proper double-entry bookkeeping — daily sales summary විතරක් නෙමෙයි. Accounts ඕන shops විතරක් enable කරන්න.',
      'Overview — accounts snapshot, recent journals, key balances.',
      'GL Journals — manual debit/credit entries — adjustments, transfers, corrections.',
      'GL Reports — trial balance, P&L, balance sheet.',
      'AR / AP — Receivable (customers owe you) / Payable (you owe suppliers).',
      'Cash & Bank — cash drawers සහ bank accounts track; deposits/withdrawals reconcile.',
      'VAT / Tax — VAT registered නම් tax entries සහ reports.',
      'Petty Cash — petty cash float එකෙන් small daily expenses.',
      'Payroll — staff salary records (system එකෙන් payroll run කරනවා නම්).',
      'Periods — accounting periods open/close — පරණ months accidentally change වෙන්න එපා.',
      'Audit Trail — accounting changes log — control/review.',
      'Accounting Settings — fiscal year, default accounts, posting rules.',
      'Note: POS sales සහ supplier payments auto-post වෙන්න පුළුවන් integration enabled නම්.',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Enable & initial setup',
        titleSi: 'Step 1 — Enable & setup',
        stepsEn: [
          'Confirm Accounting feature is enabled (Settings → Features / plan).',
          'Finance → Accounting → Settings.',
          'Set fiscal year start, default accounts, posting rules.',
          'Review chart of accounts on Overview page.',
          'Open first accounting Period if required.',
        ],
        stepsSi: [
          'Accounting feature enabled confirm.',
          'Finance → Accounting → Settings.',
          'Fiscal year, default accounts set.',
          'Overview → chart of accounts review.',
          'First Period open.',
        ],
      },
      {
        titleEn: 'Step 2 — Daily bookkeeping',
        titleSi: 'Step 2 — Daily bookkeeping',
        stepsEn: [
          'POS sales may auto-post — check Overview for new journal entries.',
          'Supplier payments may auto-post when recorded.',
          'Manual entries: GL Journals → New Journal → debit + credit lines must balance.',
          'Petty Cash: record small shop expenses from float.',
          'Cash & Bank: record deposits and withdrawals; reconcile with bank statement.',
        ],
        stepsSi: [
          'POS sales auto-post — Overview check.',
          'Supplier payments auto-post (enabled නම්).',
          'Manual: GL Journals → debit/credit balance.',
          'Petty Cash — small expenses.',
          'Cash & Bank — deposits/withdrawals reconcile.',
        ],
      },
      {
        titleEn: 'Step 3 — AR / AP & tax',
        titleSi: 'Step 3 — AR / AP & tax',
        stepsEn: [
          'AR / AP: see customers who owe you and suppliers you owe.',
          'Match with Customers page outstanding and Supplier Payments.',
          'VAT / Tax: enter tax entries if shop is VAT registered.',
          'Run tax reports before filing.',
        ],
        stepsSi: [
          'AR / AP — receivable/payable lists.',
          'Customers outstanding + Supplier Payments match.',
          'VAT / Tax entries (registered නම්).',
          'Tax reports run.',
        ],
      },
      {
        titleEn: 'Step 4 — Month end & reports',
        titleSi: 'Step 4 — Month end',
        stepsEn: [
          'GL Reports → Trial Balance — debits must equal credits.',
          'Run Profit & Loss and Balance Sheet for the period.',
          'Payroll journals if using Payroll module.',
          'Review Audit Trail for unexpected changes.',
          'Close accounting Period — locks past month from edits.',
        ],
        stepsSi: [
          'GL Reports → Trial Balance.',
          'P&L + Balance Sheet.',
          'Payroll (use නම්).',
          'Audit Trail review.',
          'Period close — past month lock.',
        ],
      },
    ],
  },
  {
    id: 'invoice-settings',
    titleEn: 'Invoice & Bill Settings',
    titleSi: 'Invoice & Bill Settings',
    itemsEn: [
      'Settings → Invoice — configure logo, shop name, address, phone on bills.',
      'Print format: Thermal 58mm, Thermal 80mm, or Stock Form (9.5×11 tractor invoice).',
      'POS auto-print — automatically print bill when sale completes.',
      'Warranty & Service Terms and Terms & Conditions print at the bottom of stock-form bills.',
      'Toggle which fields appear on thermal receipts (SKU, IMEI, customer, warranty block).',
    ],
    itemsSi: [
      'Settings → Invoice — logo, shop name, address, phone.',
      'Print format: Thermal 58mm / 80mm / Stock Form.',
      'POS auto-print — sale complete වෙද්දී auto print.',
      'Warranty Terms සහ T&C stock-form bill bottom එකේ.',
      'Thermal receipt fields on/off.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Set up bills',
        titleSi: 'Step-by-step — Bill setup',
        stepsEn: [
          'Sidebar → Settings → Invoice tab.',
          'Upload shop logo and enter shop name, address, phone.',
          'Choose print format: Thermal 58mm, 80mm, or Stock Form (tractor invoice).',
          'Turn POS auto-print ON if bill should print after every sale.',
          'Edit Warranty Terms and Terms & Conditions for stock-form bills.',
          'Toggle thermal receipt fields (SKU, IMEI, customer, warranty block).',
          'Save — test with a small POS sale and F5 reprint.',
        ],
        stepsSi: [
          'Settings → Invoice tab.',
          'Logo upload + shop name, address, phone.',
          'Print format select (58mm / 80mm / Stock Form).',
          'POS auto-print ON/OFF.',
          'Warranty Terms + T&C edit.',
          'Thermal fields toggle.',
          'Save → test sale + F5 reprint.',
        ],
      },
    ],
  },
  {
    id: 'whatsapp',
    titleEn: 'WhatsApp',
    titleSi: 'WhatsApp',
    itemsEn: [
      'Connect shop WhatsApp from the WhatsApp page (scan QR code).',
      'After a sale, send invoice PDF or message to the customer from the success screen.',
    ],
    itemsSi: [
      'WhatsApp page → QR scan → connect.',
      'Sale complete → customer ට invoice send.',
    ],
    stepGroups: [
      {
        titleEn: 'Step-by-step — Connect WhatsApp',
        titleSi: 'Step-by-step — WhatsApp connect',
        stepsEn: [
          'Sidebar → WhatsApp.',
          'Click Connect and scan QR code with shop WhatsApp on your phone.',
          'Wait until status shows Connected.',
          'Keep phone online — disconnected WhatsApp stops sending.',
        ],
        stepsSi: [
          'Sidebar → WhatsApp.',
          'Connect → QR scan (shop phone).',
          'Connected status wait.',
          'Phone online තියන්න.',
        ],
      },
      {
        titleEn: 'Step-by-step — Send invoice after sale',
        titleSi: 'Step-by-step — Invoice send',
        stepsEn: [
          'Complete a POS sale as normal.',
          'On success screen click Send WhatsApp or WhatsApp Invoice.',
          'Confirm customer phone number.',
          'Message/PDF sends to customer chat.',
        ],
        stepsSi: [
          'POS sale complete.',
          'Success screen → Send WhatsApp.',
          'Phone confirm.',
          'Customer chat එකට send.',
        ],
      },
    ],
  },
  {
    id: 'roles',
    titleEn: 'User Roles & Permission Matrix',
    titleSi: 'User Roles සහ Permission Matrix',
    itemsEn: [
      'Owner — full access including settings, staff, and the permission matrix.',
      'Manager / Cashier / Technician — access follows the Role Permission Matrix (Hide / View / Edit).',
      'Open Sidebar → Role Permissions (or Staff & Roles → Permission Matrix tab).',
      'Click a cell to cycle Hide → View → Edit, then Save. Owner column always stays Edit.',
      'Full step-by-step guide: Dashboard → Permissions Guide.',
      'Add staff under Staff & Roles and assign a role + at least one branch.',
    ],
    itemsSi: [
      'Owner — settings, staff, matrix සියල්ල.',
      'Manager / Cashier / Technician — Role Permission Matrix අනුව (Hide / View / Edit).',
      'Sidebar → Role Permissions (හෝ Staff & Roles → Permission Matrix tab).',
      'Cell click: Hide → View → Edit → Save. Owner column හැම වෙලේම Edit.',
      'සම්පූර්ණ guide: Dashboard → Permissions Guide.',
      'Staff & Roles යටතේ staff add කරලා role + branch assign කරන්න.',
    ],
    stepGroups: [
      {
        titleEn: 'Step 1 — Add staff user',
        titleSi: 'Step 1 — Staff add',
        stepsEn: [
          'Sidebar → Staff & Roles.',
          'Click Add Staff.',
          'Enter name, phone/email, and login details.',
          'Assign role: Owner, Manager, Cashier, or Technician.',
          'Select at least one branch they can work on.',
          'Save — staff can log in with their credentials.',
        ],
        stepsSi: [
          'Sidebar → Staff & Roles.',
          'Add Staff.',
          'Name, phone/email, login.',
          'Role assign.',
          'Branch select.',
          'Save → login.',
        ],
      },
      {
        titleEn: 'Step 2 — Set permission matrix',
        titleSi: 'Step 2 — Permission matrix',
        stepsEn: [
          'Open Role Permissions (or Staff & Roles → Permission Matrix tab).',
          'Each row is a module; columns are roles.',
          'Click a cell to cycle Hide → View → Edit.',
          'Owner column always stays Edit — do not restrict Owner.',
          'Click Save after changes.',
          'Staff see only menu items their role allows.',
        ],
        stepsSi: [
          'Role Permissions / Permission Matrix tab.',
          'Row = module, column = role.',
          'Cell click: Hide → View → Edit.',
          'Owner column Edit only.',
          'Save.',
          'Staff role අනුව menu.',
        ],
      },
    ],
  },
  {
    id: 'faq',
    titleEn: 'Common Questions',
    titleSi: 'නිතර අහන ප්‍රශ්න',
    itemsEn: [
      'Bill not printing? Allow browser pop-ups; check Settings → Invoice print type; press F5 to reprint.',
      'Warranty not created? Select a customer; product must have warranty months > 0.',
      'Insufficient stock? Add stock via Add Stock or receive a purchase order.',
      'Wrong price on bill? Edit price in cart before checkout.',
      'Need help? Call Hexalyte Innovation — 070 313 0100.',
    ],
    itemsSi: [
      'Bill print නැහැ? Pop-ups allow; Settings → Invoice; F5 reprint.',
      'Warranty නැහැ? Customer select; warranty months > 0.',
      'Stock insufficient? Add Stock / PO receive.',
      'Price වැරදි? Checkout එකට පෙර cart price edit.',
      'Help: Hexalyte Innovation — 070 313 0100.',
    ],
    stepGroups: [
      {
        titleEn: 'Quick fixes — step by step',
        titleSi: 'Quick fixes — step by step',
        stepsEn: [
          'Bill not printing? Allow browser pop-ups → Settings → Invoice check format → F5 reprint.',
          'Warranty missing? Select customer in POS + product warranty months must be > 0.',
          'Insufficient stock? Inventory → Add Stock or receive Purchase Order.',
          'Wrong price? Edit in cart before F9 Checkout — not after sale.',
          'Still stuck? Call Hexalyte Innovation — 070 313 0100.',
        ],
        stepsSi: [
          'Bill නැහැ? Pop-ups allow → Settings Invoice → F5.',
          'Warranty නැහැ? Customer select + warranty months > 0.',
          'Stock insufficient? Add Stock / PO receive.',
          'Price වැරදි? F9 එකට පෙර cart edit.',
          'Help: 070 313 0100.',
        ],
      },
    ],
  },
]

export const USER_MANUAL_WORKFLOW_EN = [
  'Open POS',
  'F7 Day Start (if your shop uses it)',
  'F2 Select customer (warranty / credit)',
  'Add products or scan IMEI',
  'Edit price or warranty if needed',
  'F9 Checkout → payment',
  'Bill prints — F5 reprint if needed',
  'F10 New sale',
  'F11 Day End / Daily Closing at end of day',
]

export const USER_MANUAL_WORKFLOW_SI = [
  'POS open',
  'F7 Day Start (use කරනවා නම්)',
  'F2 Customer select',
  'Products add / IMEI scan',
  'Price / warranty edit',
  'F9 Checkout',
  'Bill print — F5 reprint',
  'F10 New sale',
  'F11 Day End / Daily Closing',
]
